[[atividades8]]
=== Atividades

. Calcule as derivadas das seguintes funções:
+
[width="100%",cols="<,<",frame="none",grid="none"]
|======================
| i. latexmath:[$F(x)=\mathlarger{\int}^{2x}_{1} \cosh(2t^2+1)dt$].
|ii. latexmath:[$ F(x)= \mathlarger{\int}^{x}_{2} \left( \mathlarger{\int}^{y}_{8} \dfrac{1}{1+t^2+{\rm sen}^2(t)}dt \right)dy    $].
|iii. latexmath:[$ F(x)= {\rm sen}\left[\! \mathlarger{\int}^{x}_{0} {\rm sen}\left(\! \mathlarger{\int}^{y}_{0} \!{\rm sen}^3(t)\,dt\! \right)dy   \!\right\] $].
|iv. latexmath:[$F(x)=\mathlarger{\int}^{x^2}_{x^3} \dfrac{t^5}{1+t^4}dt$].
|v. latexmath:[$F(x)=\mathlarger{\int}^{e^x}_{x^2} x(t^2+1)dt$].
|
|=======================
. Se latexmath:[$\mathlarger{\int}^{\frac{1}{3x+1}}_{0} f(t) dt\,=\dfrac{2}{ax}+ax$], calcule os valores de latexmath:[$a$], de modo que latexmath:[$f\left(\dfrac{1}{4} \right)=\dfrac{16}{3}$].

. Calcule latexmath:[$f(2)$] supondo que a função latexmath:[$f$] é contínua e verifica a equação dada latexmath:[$\forall\,x\geq 0$] 
+
[width="100%",cols="<,<",frame="none",grid="none"]
|======================
|i. latexmath:[$\mathlarger{\int}^{x}_{0} f(t)dt=x^2(1+x)$].
|ii. latexmath:[$\mathlarger{\int}^{x^2}_{0} f(t)dt=x^2(1+x)$].
|iii. latexmath:[$\mathlarger{\int}^{f(x)}_{0} t^2dt=x^2(1+x)$].
|iv. latexmath:[$\mathlarger{\int}^{x^2(1+x)}_{0} f(t)dt=x$].
|======================

. Calcule o valor das seguintes integrais definidas:
+
[width="100%",cols="<,<,<",frame="none",grid="none"]
|======================
|i. latexmath:[$\mathlarger{\int}^{2}_{-2} x^3dx$].
|ii. latexmath:[$\mathlarger{\int}^{2}_{-1} (x+1)^3dx$]. 
|iii. latexmath:[$\mathlarger{\int}^{1/2}_{0} \dfrac{1}{\sqrt{1-x^2}}dx$]. 
|iv. latexmath:[$\mathlarger{\int}^{2}_{1} \dfrac{x}{1+x^2}dx$]. 
|v. latexmath:[$\mathlarger{\int}^{4}_{2} \dfrac{x^2}{x-1}dx$].
|vi. latexmath:[$\mathlarger{\int}^{e}_{1} \ln(x)\,dx$].
|======================
+
[width="100%",cols="<,<",frame="none",grid="none"]
|======================
|vii. latexmath:[$\mathlarger{\int}^{0}_{-1} \dfrac{dx}{4x^2+8x+8}$].
|viii. latexmath:[$\mathlarger{\int}^{\sqrt{2}}_{0} \dfrac{dx}{\sqrt{2-x^2}}$].
|ix. latexmath:[$\mathlarger{\int}^{1}_{0} x^8\,e^{-x^3}dx$].
|x. latexmath:[$\mathlarger{\int}^{\pi/3}_{-\pi/3} {\rm tg} ^7( x)\, dx$].
|xi. latexmath:[$\mathlarger{\int}^{2}_{0} \dfrac{x^5}{(1+x^3)^{3/2}}dx$].
|xii. latexmath:[$\mathlarger{\int}^{0}_{1} x^8\,(1-x^3)^{5/4}dx$].
|xiii. latexmath:[$\mathlarger{\int}^{1}_{0} \sqrt{x} \sqrt{2-x}\,dx$].
|xiv. latexmath:[$\mathlarger{\int}^{1}_{0} \dfrac{xe^x}{(1+x)^2}dx$].
|xv. latexmath:[$\mathlarger{\int}^{1}_{0} \ln(\sqrt{2-x})\,dx$].
|xvi. latexmath:[$\mathlarger{\int}^{\pi/3}_{\pi/4} {\rm cotg}(x)\,(\ln ({\rm sen\,}(x)))dx$].
|xvii. latexmath:[$\mathlarger{\int}^{2\pi}_{0} \| {\rm sen\,}(x) -\cos (x) \| \,dx$].
|xviii. latexmath:[$\mathlarger{\int}^{4}_{-2} \dfrac{\|x+1\|}{\|x+6\|}dx$].
|======================



. Determine se as seguintes integrais são convergentes ou divergentes:
+
[width="100%",cols="<,<,<",frame="none",grid="none"]
|======================
|i. latexmath:[$\mathlarger{\int}^{+\infty}_{0} {\rm sen\,}x\,dx$].
|ii. latexmath:[$\mathlarger{\int}^{+\infty}_{0} e^{-x} dx$].
|iii. latexmath:[$\mathlarger{\int}^{+\infty}_{-\infty} \|x\|e^{x^2} dx$].
|iv. latexmath:[$\mathlarger{\int}^{+\infty}_{0} \dfrac{dx}{\sqrt{e^x}}$].
|v. latexmath:[$\mathlarger{\int}^{1}_{-2} \dfrac{dx}{x^3} $].
|vi. latexmath:[$\mathlarger{\int}^{+\infty}_{-\infty} \dfrac{dx}{4x^2+1} $].
|vii. latexmath:[$\mathlarger{\int}^{0}_{-2} \dfrac{dx}{\sqrt[3\]{x+1}}$].
|viii. latexmath:[$\mathlarger{\int}^{1}_{0} \dfrac{e^{1/x}}{x^3}$].
|ix. latexmath:[$\mathlarger{\int}^{+\infty}_{-\infty} \dfrac{dx}{x^2+2x+2}$].
|x. latexmath:[$\mathlarger{\int}^{+\infty}_{1} \dfrac{dx}{x\sqrt{x^2-1}} $].
|xi. latexmath:[$\mathlarger{\int}^{1}_{0} \dfrac{dx}{x^3 -5x^2} $].
|xii. latexmath:[$\mathlarger{\int}^{+\infty}_{-\infty} \dfrac{dx}{e^x + e^{-x}} $].
|xiii. latexmath:[$\mathlarger{\int}^{+\infty}_{1} \dfrac{dx}{x\sqrt{1+x^3}} $].
|xiv. latexmath:[$\mathlarger{\int}^{+\infty}_{-\infty} e^{(x-e^x)} dx $].
|xv. latexmath:[$\mathlarger{\int}^{4}_{0}\dfrac{x\,dx}{\sqrt{16-x^2}} $].
|xvi. latexmath:[$\mathlarger{\int}^{1}_{0} \dfrac{dx}{\sqrt{x-x^2}} $].
|xvii. latexmath:[$\mathlarger{\int}^{4}_{1} \dfrac{dx}{x^2-4} $].
|xviii. latexmath:[$\mathlarger{\int}^{2}_{1} \dfrac{x^2}{x-1}dx$].
|======================

. Calcule a área da região limitada pelas curvas dadas:
+
[width="100%",cols="<,<",frame="none",grid="none"]
|======================
|  i. latexmath:[$\,\, y=(x-1)^3$], latexmath:[$x=3$], latexmath:[$x=8$] e o eixo latexmath:[$x$].
| ii. latexmath:[$\,\, y=4-x^2$] e o eixo latexmath:[$y$].
|iii. latexmath:[$\,\, y=2\sqrt{x}$], latexmath:[$x=0$], latexmath:[$x=4$] e o eixo latexmath:[$x$].
| iv. latexmath:[$\,\, y=12-x^2$], latexmath:[$x=-3$], latexmath:[$x=-2$] e o eixo latexmath:[$x$].
|  v. latexmath:[$\,\, y=x^2$], latexmath:[$y=4-3x^2$].
|vi. latexmath:[$y=x^2+2x-3$], latexmath:[$x=-2$], e os eixos latexmath:[$x$] e latexmath:[$y$].
|vii. latexmath:[$y=9-x^2$] e latexmath:[$y=x^2+1$].
|viii. latexmath:[$y=3x-x^2$] e latexmath:[$y=x^2-x$].
|ix. latexmath:[$y=x^3+x$], latexmath:[$x=0$], latexmath:[$y=2$] e latexmath:[$y=0$].
|x. latexmath:[$y=x^3-3x^2+2x+2$] e latexmath:[$y=2x^2-4x+2$].
|xi. latexmath:[$y=x^3+x-4$], latexmath:[$y=x$] e latexmath:[$y=8-x$].
|xii. latexmath:[$y=\|x-2\|$], latexmath:[$y+x^2=0$], latexmath:[$x=1$] e latexmath:[$x=3$].
|xiii. latexmath:[$y=\dfrac{x^2-4}{x^2-16}$], latexmath:[$x=-3$], latexmath:[$x=3$] e latexmath:[$y=0$].
|xiv. latexmath:[$y=x^3+3x^2+2$] e latexmath:[$y=x^3+6x^2-25$].
|xv. latexmath:[$y=x^2$], latexmath:[$2y=x^2$] e latexmath:[$y=2x$].
|xvi. latexmath:[$y=x^4$] e latexmath:[$y=8x$].
|xvii. latexmath:[$y=\dfrac{1}{1+x^2}$] e latexmath:[$2y=x^2$].
|xviii. latexmath:[$y=\|20x+x^2-x^3\|$] e latexmath:[$y=0$].
|xix. latexmath:[$y=\dfrac{8}{x^4+4}$], latexmath:[$y=0$], latexmath:[$x=0$] e latexmath:[$x=4$].
|xx. latexmath:[$y=\|x-1\|$], latexmath:[$y=x^2-2x$], latexmath:[$x=0$] e latexmath:[$x=2$].
|xxi. latexmath:[$y=\|x-2\|-\|x-6\|$] e latexmath:[$x-y=4$].
|xxii. latexmath:[$y=x^2$], latexmath:[$2y=x^2$] e latexmath:[$y=2x$].
|xxiii. latexmath:[$y=60(x^5\! -\!x^4\! +\!x^3)$], latexmath:[$y\!=\!-2x$] e latexmath:[$x^2\!=\!1$].
|xxiv. latexmath:[$x+y-y^3=0$] e latexmath:[$x-y+y^2=0$].
|======================

. Calcule o volume do sólido gerado pela rotação da região latexmath:[$R$] em torno da reta latexmath:[$L$] onde:

... latexmath:[$L\,:\,y=0$]; latexmath:[$R$] é limitada por latexmath:[$y=x^2$] e latexmath:[$y=4x$].
... latexmath:[$L\,:\,y=0$]; latexmath:[$R$] é limitada por latexmath:[$y=x^3-5x^2+8x-4$] e latexmath:[$y=0$].
... latexmath:[$L\,:\,y=0$]; latexmath:[$R$] é limitada por latexmath:[$x^2 +(y-3)^2=1$].
... latexmath:[$L\,:\,y=4$]; latexmath:[$R$] é limitada por latexmath:[$y^2=4(2-x)$] e latexmath:[$x=0$].
... latexmath:[$L\,:\,y=4$]; latexmath:[$R$] é limitada por latexmath:[$x^2+y^2=1$].
... latexmath:[$L\,:\,y=-2$]; latexmath:[$R$] é limitada por latexmath:[$y^2=x$] e latexmath:[$y=x^2$].
... latexmath:[$L\,:\,x=0$]; latexmath:[$R$] é limitada por latexmath:[$y=\sqrt{x^2+10}$], latexmath:[$x=3$] e latexmath:[$x=4$].
... latexmath:[$L\,:\,y=0$]; latexmath:[$R$] é limitada por latexmath:[$x=\sqrt{y^2+4}$], latexmath:[$y=0$], latexmath:[$y=2$] e latexmath:[$x=0$].
... latexmath:[$L\,:\,y=-1$]; latexmath:[$R$] é limitada por latexmath:[$y=\sqrt{x^2-3}$], latexmath:[$y=x-1$] e latexmath:[$y=0$].
... latexmath:[$L\,:\,x=1$]; latexmath:[$R$] é limitada por latexmath:[$y=|x^2-2x-3|$], latexmath:[$y+1=0$], latexmath:[$x=2$] e latexmath:[$x=4$].
... latexmath:[$L\,:\,x=-1$]; latexmath:[$R$] é limitada por latexmath:[$y=\sqrt{x}$], latexmath:[$x=0$] e latexmath:[$y=2$].
... latexmath:[$L\,:\,x=0$]; latexmath:[$R$] é limitada por latexmath:[$y=x^5$], latexmath:[$x=-1$], latexmath:[$x=-2$] e latexmath:[$y=-1$].
... latexmath:[$L\,:\,x=4$]; latexmath:[$R$] é limitada por latexmath:[$y=(x-1)^2$] e latexmath:[$y=x+1$].
... latexmath:[$L\,:\,x=0$]; latexmath:[$R$] é limitada por latexmath:[$y=3x^2$], latexmath:[$y=4-6x^2$].
... latexmath:[$L\,:\,x=0$]; latexmath:[$R$] é limitada por latexmath:[$x=y^2$] e latexmath:[$x=8-y^2$].
... latexmath:[$L\,:\,y=2$]; latexmath:[$R$] é limitada por latexmath:[$y=\ln(x)$], latexmath:[$y=0$], latexmath:[$x=0$] e latexmath:[$y=2$].
... latexmath:[$L\,:\,y=2$]; latexmath:[$R$] é limitada por latexmath:[$y=\sqrt{x}$], latexmath:[$y=0$] e latexmath:[$x=4$].

. Calcule o comprimento de arco  da curva latexmath:[$y^2=4x-x^2$], compreendido entre os dois pontos de interseção com o eixo latexmath:[$x$].
. Calcule o comprimento de arco  da curva latexmath:[$y=\ln(x)$], a partir de latexmath:[$x=\sqrt{3}$] e latexmath:[$x=\sqrt{8}$].
. Calcule o comprimento de arco  da curva latexmath:[$5y^3=x^2$], compreendido  dentro da circunferência latexmath:[$x^2+y^2=6$].
. Calcule o comprimento de arco  da curva latexmath:[$y=e^x$], compreendido entre os pontos latexmath:[$(0,1)$] e latexmath:[$(1,e)$].
. Calcule o comprimento de arco  da curva latexmath:[$y=\ln(1-x^2)$], a partir de latexmath:[$x=\dfrac{1}{4}$] e latexmath:[$x=\dfrac{3}{4}$].
. Calcule o comprimento de arco  da curva latexmath:[$9y^2=4x^3$], a partir da origem até o ponto latexmath:[$(3,2\sqrt{3})$].
. Calcule o comprimento de arco  total do arco da curva latexmath:[$y=2\sqrt{x}$], a partir de latexmath:[$x=0$] até latexmath:[$x=1$].
. Calcule o comprimento de arco  da curva latexmath:[$x= \dfrac{y^2}{2} - \dfrac{1}{2} \ln y$], a partir de latexmath:[$y=1$] até latexmath:[$y=e$].
. Calcule o comprimento de arco  da curva latexmath:[$y=\ln \left(\dfrac{e^x+1}{e^x-1}\right)$], a partir de latexmath:[$x=1$] até latexmath:[$x=2$].
. Calcule o comprimento de arco  da curva latexmath:[$9a y^2=x(x-3a)^2$], a partir de latexmath:[$x=0$] até latexmath:[$x=3a$].
. Calcule o comprimento de arco  da curva latexmath:[$y=\ln (1-x^2)$], a partir de latexmath:[$x=0$] até latexmath:[$x=1/2$].


. Calcule a área da superfície de revolução obtida ao girar as curvas dadas em torno do eixo indicado:

... A curva latexmath:[$f(x)=\dfrac{1}{9}x^3$]; a partir de latexmath:[$x=0$] até latexmath:[$x=2$]; em torno do eixo latexmath:[$x$].
... A curva latexmath:[$6a^2xy = x^4+3a^4$]; a partir de latexmath:[$x=a$] até latexmath:[$x=2a$]; em torno do eixo latexmath:[$x$].
... A curva latexmath:[$y^2+4x=2 \ln( y)$]; a partir de latexmath:[$y=1$] até latexmath:[$y=2$]; em torno do eixo latexmath:[$x$].
... A curva latexmath:[$y=e^{-x}$]; a partir de latexmath:[$x\geq 0$]; em torno do eixo latexmath:[$x$].
... A curva latexmath:[$y^2 =4ax$]; a partir de latexmath:[$x=0$] até latexmath:[$x=3a$]; em torno do eixo latexmath:[$x$].
... A curva latexmath:[$x=y^3$]; a partir de latexmath:[$y=0$] até latexmath:[$y=3$]; em torno do eixo latexmath:[$y$].
... A curva latexmath:[$x^2+4y^2=16$]; em torno do eixo latexmath:[$y$].
... A curva latexmath:[$y=x^2$]; a partir de latexmath:[$x=1$] até latexmath:[$x=2$]; em torno do eixo latexmath:[$y$].
... A curva latexmath:[$y=x^{3/2}$]; a partir de latexmath:[$x=1$] até latexmath:[$x=8$]; em torno de latexmath:[$y=1$].
... A curva latexmath:[$y=x^3$]; a partir de latexmath:[$x=1$] até latexmath:[$x=2$]; em torno de latexmath:[$y=-1$].
... A curva latexmath:[$y=4+e^x$]; a partir de latexmath:[$x=0$] até latexmath:[$x=1$]; em torno de latexmath:[$y=4$].


// Sempre terminar o arquivo com uma nova linha.

