== Números Reais

:cap: cap1

.Objetivos do capítulo
____________________
Ao final deste capítulo você deverá ser capaz de:

* Dados dois números reais, reconhecer a relação de ordem estabelecida entre eles e suas principais propriedades;
* Determinar as raízes de uma equação dada;
* Determinar o conjunto solução de uma inequação dada;
* Dominar o conceito de valor absoluto;
* Entender o conceito do sistema dos números reais e saber diferenciar os subconjuntos que o integram: naturais, inteiros, racionais e irracionais;
* Familiarizar-se com o Axioma do Supremo.
____________________


O sistema dos números reais que conhecemos atualmente foi obtido depois de muitas reflexões por parte do homem. 
Desde o início de nossa civilização já se conheciam os números inteiros positivos, ou seja, latexmath:[$1, 2, 3, \dots$]
 Os números inteiros, tão grandes quanto latexmath:[$100000$], já eram utilizados no Egito em épocas como latexmath:[$300$] a. C.

Na aritmética de números inteiros positivos, que desenvolveram os antigos egípcios e babilônios, podiam 
efetuar-se  as operações de adição e multiplicação, embora essa última não tenha sido desenvolvida por completo. 
Além disso, naquela época já se conheciam certas frações, isto é, os números racionais. Por outro lado, os Babilônios tiveram maior êxito no desenvolvimento
 da aritmética e da álgebra, e a notação que eles usavam também era superior a dos egípcios, com a diferença que eles trabalhavam na base 
 latexmath:[$60$] e não na base latexmath:[$10$].

Nosso sistema decimal foi criado pelos Hindus e introduzido na Europa Ocidental no século XII, mediante a tradução de textos
 árabes, porém, essa notação demorou para ter uma aceitação geral, e muito depois disso veio a aceitação dos números negativos, a qual 
 aconteceu apenas no final do século XVI, época em que eram descartadas as raízes negativas das equações.

Ainda que a necessidade dos números irracionais, tais como latexmath:[$\sqrt{2}$] e latexmath:[$\pi$], já tinha se  apresentado aos matemáticos da antiga Grécia no seus estudos geométricos, não foram introduzidos métodos satisfatórios de construção dos 
números reais a partir dos racionais até finais do século XIX, quando os matemáticos conseguiram propor um ponto de partida 
para a construção total dos números reais, abordagem atualmente utilizada.

Embora seja muito interessante apresentar o construção do conjunto dos números reais passo a passo, o foco deste livro não é o construtivo, pois assumiremos que existam certos objetos, chamados de números reais, que verificam 
os 11 axiomas a serem enunciados neste capítulo. Todas as propriedades dos números reais que serão apresentadas aqui, ou estão entre 
estes axiomas, ou podem ser deduzidas a partir deles.

Portanto, neste capítulo revisaremos o sistema dos números reais, desigualdades e intervalos, equações, inequações, valor absoluto, 
Axioma do Supremo, e resolveremos alguns problemas usando a teoria apresentada.

=== Sistema dos Números Reais

Um conjunto não vazio de suma importância, para o bom entendimento de toda a teoria apresentada neste livro, é o conjunto dos *números reais*, denotado por latexmath:[$\mathbb{R}$]. Cada elemento de latexmath:[$\mathbb{R}$] é chamado de *número real*.


Os números reais são identificados por pontos numa reta. E essa identificação dá-se da seguinte maneira:

image::images/{cap}/retareal.eps[scaledwidth="50%"]

Dada uma reta (por conveniência horizontal) e uma unidade de medida arbitrária, fixamos 
o ponto latexmath:[$0$] da reta, logo, a cada número real latexmath:[$x$] se identifica com o ponto que está situado a latexmath:[$x$] unidades à direita do latexmath:[$0$], se latexmath:[$x>0$], e com o ponto situado a latexmath:[$-x$] unidades à esquerda  do latexmath:[$0$], se latexmath:[$x<0$]. 

Essa correspondência entre os números reais e os pontos da reta é *biunívoca*, isto é, para cada número real há um único ponto correspondente na reta, e para cada ponto na reta há um único número real correspondente. No decorrer deste livro, não faremos nenhuma diferenciação entre ambos elementos.

Logo, o *((sistema dos números reais))*, denotado por latexmath:[$(\mathbb{R};+;\cdot;<)$], é o conjunto latexmath:[$\mathbb{R}$] fornecido de duas operações, *adição*  latexmath:[$(+)$] e 
 *multiplicação* latexmath:[$(\cdot)$], de uma *relação de ordem* latexmath:[$(<)$] (lê-se *menor que*) e de um axioma chamado  
 *Axioma do Supremo*. Para simplificar a notação usaremos somente latexmath:[$\mathbb{R}$]. 

==== Adição e Multiplicação de Números Reais
Embora as operações de adição e multiplicação sejam duas operações aritméticas com as quais estamos muito acostumados desde o início dos nossos estudos na escola, a adição e a multiplicação de números reais são duas operações internas em latexmath:[$\mathbb{R}$] e são definidas, formalmente, como segue:

Adição:: Dados latexmath:[$a$] e  latexmath:[$b\in \mathbb{R}$] existe um único latexmath:[$w \in \mathbb{R}$], chamado de *soma* de latexmath:[$a$] e latexmath:[$b$], tal que latexmath:[$w=a+b$]. 


Multiplicação:: Dados latexmath:[$a$] e latexmath:[$b\in \mathbb{R}$] existe um único latexmath:[$z \in \mathbb{R}$], chamado de *produto* de latexmath:[$a$] e latexmath:[$b$], tal que latexmath:[$z=a\cdot b$]. 

A adição e  multiplicação de números reais são regidos pelos seguintes axiomas:

Axioma 1::: latexmath:[$a+b=b+a, \quad \forall\,a,b\in \mathbb{R}$].

Axioma 2::: latexmath:[$(a+b)+c=a+(b+c), \quad \forall\,a,b,c\in \mathbb{R}$].

Axioma 3::: Existe o número real *zero*, denotado por latexmath:[$0$], tal que latexmath:[$a+0=0+a=a,\quad \forall\, a\in \mathbb{R}$].

Axioma 4::: Para cada número real latexmath:[$a$] existe um real chamado de *oposto* de latexmath:[$a$], denotado por latexmath:[$-a$], tal que latexmath:[$a+(-a)=0$].

Axioma 5::: latexmath:[$a\cdot b=b\cdot a,\quad \forall\,a,b\in \mathbb{R}$].
Axioma 6::: latexmath:[$(a\cdot b)\cdot c=a\cdot(b\cdot c), \quad  \forall\,a,b,c\in \mathbb{R}$].
Axioma 7::: Existe o número real *um*, denotado por latexmath:[$1$], tal que latexmath:[$a\cdot 1=1\cdot a=a$], latexmath:[$\,\,\, \forall\, a\in \mathbb{R}$].
Axioma 8::: Para cada número real latexmath:[$a$], diferente de zero, existe um número real chamado de *inverso* de latexmath:[$a$], denotado por latexmath:[$a^{-1}$] ou latexmath:[$\dfrac{1}{a}$], tal que latexmath:[$a\cdot a^{-1}=a^{-1}\cdot a=1$].

Axioma 9::: latexmath:[$a(b+c)=a\cdot b + a\cdot c,\quad  \forall\,a,b,c\in \mathbb{R}$]

[NOTE]
====
.. Os *Axiomas 1* e *5* são conhecidos como *axiomas comutativos* para a soma e multiplicação, respectivamente;
.. Os *Axiomas 2* e *6* são conhecidos como *axiomas associativos* para a soma e multiplicação, respectivamente;
.. O *Axioma 9* é conhecido como *axioma distributivo* e relaciona a adição e multiplicação de números reais.
 
====

O seguinte teorema enuncia as propriedades dessas duas operações. 

[options="unbreakable"]
Teorema 1.1:: Sejam latexmath:[$a$, $b$ e $ c \in \mathbb{R}$]. Então:
...  Os números latexmath:[$0,\,\,1,\,\,-a$] e latexmath:[$a^{-1}$] são únicos;
...  latexmath:[$a=-(-a)$];
...  Se latexmath:[$a\neq 0$], então  latexmath:[$a=(a^{-1})^{-1}$];
...  latexmath:[$a\cdot 0=0\cdot a= 0$];
...  latexmath:[$-a=(-1)\cdot a$];
...  latexmath:[$a\cdot (-b)=(-a)\cdot b$];
...  latexmath:[$(-a)\cdot (-b)=a\cdot b$];
...  Se latexmath:[$a+c=b+c$], então latexmath:[$a=b$];
...  Se latexmath:[$a \cdot c=b\cdot c$] e latexmath:[$c\neq 0$], então latexmath:[$a=b$];
...  latexmath:[$a\cdot b=0$] se, e somente se, latexmath:[$a=0$] ou latexmath:[$b=0$];
...  latexmath:[$a\cdot b\neq 0$] se, e somente se, latexmath:[$a\neq0$] e latexmath:[$b\neq0$];
...  latexmath:[$a^2=b^2$] se, e somente se, latexmath:[$a=b$] ou latexmath:[$a=-b$].	

[NOTE]
====
latexmath:[$0$ e  $1$] também são conhecidos como elementos neutros para a *adição* e para a *multiplicação*, respectivamente;

//.. latexmath:[$-a$ e $a^{-1}$], do item(i) do teorema acima, dizem ao respeito da unicidade do *oposto* e do *inverso*, respectivamente.

====



==== Subtração e Divisão de Números  Reais

Subtração::  Dados latexmath:[$a$] e  latexmath:[$b\in \mathbb{R}$], a  *diferença* de latexmath:[$a$] e latexmath:[$b$] é definida como latexmath:[$a-b=a+(-b)$].


Divisão ou quociente:: Dados latexmath:[$a$] e  latexmath:[$b\in \mathbb{R}$], com latexmath:[$b\neq 0$],  a *divisão* ou *quociente* de latexmath:[$a$] e latexmath:[$b$] 
é definida como latexmath:[$\dfrac{a}{b}=a\cdot( b^{-1})$].

[options="unbreakable"]
Teorema 1.2:: Sejam latexmath:[$a$, $b$, $ c$ e $d \in \mathbb{R}$]. Então:
... latexmath:[$a-b=-(b-a)$];
... latexmath:[$a-b=c$] se, e somente se, latexmath:[$a=b+c$];
... Se latexmath:[$b\neq 0$], então latexmath:[$c=\dfrac{a}{b}$] se, e somente se, latexmath:[$b\cdot c=a$];
... latexmath:[$a\cdot( b-c)=a\cdot b -a\cdot c$];
... Se latexmath:[$b\neq 0$] e latexmath:[$d\neq 0$], então latexmath:[$\dfrac{a}{b}\pm\dfrac{c}{d}=\dfrac{a\cdot d\pm b\cdot c}{b\cdot d}$].


==== Relação de Ordem

[options="unbreakable"]
Axioma 10::
Em latexmath:[$\mathbb{R}$] existe um subconjunto chamado de *reais positivos*, denotado por latexmath:[$\mathbb{R}_{++}$],  que satisfaz as seguintes propriedades:
+
--
... Se latexmath:[$a \in \mathbb{R}$], então latexmath:[$a\in \mathbb{R}_{++}$] ou latexmath:[$-a\in\mathbb{R}_{++}$] ou latexmath:[$a=0$];
... Se latexmath:[$a \in \mathbb{R}_{++}$] e latexmath:[ $b\in\mathbb{R}_{++}$], então latexmath:[$a+b\in\mathbb{R}_{++}$] e latexmath:[$a\cdot b\in\mathbb{R}_{++}$].
--


[options="unbreakable"]
Definição 1.1:: Sejam latexmath:[$a,\,b\in\mathbb{R}$]. Diz-se que: 
+
--
... latexmath:[$a$] é *menor* que latexmath:[$b$], denotado por latexmath:[$a<b$], se, e somente se, latexmath:[$b-a\in\mathbb{R}_{++}$];
... latexmath:[$a$] é *menor ou igual* que latexmath:[$b$], denotado por latexmath:[$a\leq b$], se, e somente se, latexmath:[$a<b$] ou latexmath:[$a=b$].
--

[NOTE]
===============================
.. latexmath:[$a<b$] é equivalente a latexmath:[$b>a$] e leia-se ``latexmath:[$b$] é *maior* que latexmath:[$a$]'';
.. Da mesma forma, latexmath:[$a\leq b$] é equivalente a latexmath:[$b\geq a$] e leia-se ``latexmath:[$b$] é *maior ou igual* que latexmath:[$a$]''.

===============================

O seguinte teorema enuncia as propriedades associadas à relação de ordem.

[options="unbreakable"]
Teorema 1.3:: Dados latexmath:[$a$, $b$, $c$ e $d\in \mathbb{R}$]. Então:
... latexmath:[$a=b$] ou latexmath:[$a<b$] ou latexmath:[$a>b$];
... latexmath:[$a^2\geq 0$]. Se latexmath:[$a\neq 0$], então latexmath:[$a^2>0$];
... se latexmath:[$a<b$] e latexmath:[$b<c$], então latexmath:[$a<c$]; 
... se latexmath:[$a<b$], então latexmath:[$a+c<b+c$]; 
... Se latexmath:[$a<b$] e latexmath:[$c<d$], então latexmath:[$a+c<b+d$];
... Se latexmath:[$a<b$] e latexmath:[$c>0$], então latexmath:[$a\cdot c<b\cdot c$];
... Se latexmath:[$a<b$] e latexmath:[$c<0$], então latexmath:[$a\cdot c>b\cdot c$];
... Se latexmath:[$0<a<b$] e latexmath:[$0<c<d$], então latexmath:[$a\cdot c<b\cdot d$];
... Se latexmath:[$a\neq 0$, então $a$] e latexmath:[$a^{-1}$] têm o mesmo sinal, isto é:
+
--
.. Se latexmath:[$a>0$], então latexmath:[$a^{-1}>0$],
.. Se latexmath:[$a<0$], então latexmath:[$a^{-1}<0$];   
--
+
... Se latexmath:[$0<a<b$], então  latexmath:[$0<b^{-1}<a^{-1}$];
... Se latexmath:[$a<b<0$], então  latexmath:[$b^{-1}<a^{-1}<0$];
... latexmath:[$a\cdot b>0$] se, e somente se,   (latexmath:[$a>0$] e latexmath:[$b>0$])  ou (latexmath:[$a<0$] e latexmath:[$b<0$]) ;
... latexmath:[$a\cdot b\geq 0$] se, e somente se,  (latexmath:[$a\geq0$] e latexmath:[$b\geq0$])  ou (latexmath:[$a\leq0$] e latexmath:[$b\leq0$]) 
... latexmath:[$a\cdot b<0$] se, e somente se,   (latexmath:[$a<0$] e latexmath:[$b>0$])  ou (latexmath:[$a>0$] e latexmath:[$b<0$]) ;
... latexmath:[$a\cdot b\leq 0$] se, e somente se,  (latexmath:[$a\leq 0$] e latexmath:[$b\geq0$])  ou (latexmath:[$a\geq0$] e latexmath:[$b\leq0$]) 
... Se latexmath:[$a\geq 0$] e latexmath:[$b\geq 0$], então latexmath:[$a<b$] se, e somente se,   latexmath:[$a^2<b^2$];
... latexmath:[$a^2+b^2=0$] se, e somente se,  latexmath:[$a=0$] e latexmath:[$b=0$].


[NOTE]
====
No *Teorema 1.3* temos que:

.. O item(i)  é conhecido como  *((Lei da tricotomia))*;
.. O item(iii) é conhecido como *((Lei transitiva))*; 
.. O item(iv) é conhecido como *((Lei da monotonia)) para a soma*.
====

[IMPORTANT]
====
.. Se latexmath:[$a$] e latexmath:[$b$] são dois números reias tais que latexmath:[$a^2=b$], diz-se que latexmath:[$a$] é a *raiz quadrada* de latexmath:[$b$], denotada por latexmath:[$\sqrt{b}$]. Por exemplo, latexmath:[$2$] e latexmath:[$-2$] são raízes quadradas de latexmath:[$4$], já que latexmath:[$(-2)^2=2^2=4$], e latexmath:[$\sqrt{3}$] e latexmath:[$-\sqrt{3}$] são raízes quadradas de latexmath:[$3$], pois latexmath:[$(-\sqrt{3})^2=(\sqrt{3})^2=3$].
..  Pelo  item(ii) do *Teorema 1.3*, não existe latexmath:[$a \in \mathbb{R}$] e latexmath:[$b<0$] tal que latexmath:[$a^2=b$]. Em outras palavras, *no conjunto dos números reais não existe raiz quadrada de números negativos*;
.. Se latexmath:[$a^2=0$], então deduz-se que latexmath:[$a=0$]. Portanto, latexmath:[$\sqrt{0}=0$].
====


Definição 1.2:: Uma *((desigualdade))* é uma expressão algébrica que contém relações como latexmath:[$<,\,\,\leq,\,\,>,\,\,\geq$].
 
Desta forma temos que: +
[width="100%",cols="^",frame="none",grid="none"]
|======================
| latexmath:[$x<y<z$] significa que latexmath:[$x<y$] e latexmath:[$y<z$];
|
| latexmath:[$x<y\leq z$] significa que latexmath:[$x<y$] e latexmath:[$y\leq z$]; 
|
| latexmath:[$x\leq y< z$] significa que latexmath:[$x\leq y$] e latexmath:[$y< z$]; 
|
| latexmath:[$x\leq y\leq z$] significa que latexmath:[$x\leq y$] e latexmath:[$y\leq z$]. 
|======================


Mais ainda, sejam latexmath:[$x$], latexmath:[$y$] e latexmath:[$z\in \mathbb{R}$] tais que latexmath:[$x<y<z$]. Então estas desigualdades são repŕesentadas na reta real da seguinte maneira:

[[Distância]]
.Distância entre latexmath:[$x$] e latexmath:[$y$], e distância entre latexmath:[$y$] e latexmath:[$z$]
image::images/{cap}/xyz.eps[scaledwidth="40%"]

Ou seja, latexmath:[$x$] está à esquerda de latexmath:[$y$], a uma distância de latexmath:[$y-x$] unidades e latexmath:[$z$] está à direita de latexmath:[$y$], a uma distância de latexmath:[$z-y$] unidades.


=== Equações 

Definição 1.3:: Uma *((equação))* é uma afirmação que se estabelece entre duas expressões algébricas mediante uma igualdade. 

.Tipos de Equações
===========================
* Equação de Primeiro grau
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[3x-4=2-x\]
++++++++++++++++++++++++++++++++++++++++++++

* Equação de Segundo grau
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[ x^2-4x -5=0 \]
++++++++++++++++++++++++++++++++++++++++++++

* Equação Racional
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\frac{x^2-5x+4}{x^2-4}= x+2\]
++++++++++++++++++++++++++++++++++++++++++++
* Equação Irracional
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\sqrt{x+3}+\sqrt{x+4}=-3\]
++++++++++++++++++++++++++++++++++++++++++++
* Equação Exponencial
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\sqrt[3]{3^{(5x+1)/3}}=\sqrt{9^{3(x+1)/5}}\]
++++++++++++++++++++++++++++++++++++++++++++
============================

Definição 1.4:: Dada uma equação. Diz-se que um número real latexmath:[$a$] é uma *((raiz))* da equação, ou é um *zero* da equação se ao substituir a variável da equação por latexmath:[$a$], a igualdade for verdadeira. Além disso, *resolver uma  equação* significa encontrar todas as suas raízes.



.{zwsp}
============================
Dada a equação
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[ x^2-4x -5=0 \]
++++++++++++++++++++++++++++++++++++++++++++
temos que:

.. Os números reais latexmath:[$-1$] e  latexmath:[$5$] são raízes da equação de segundo grau acima, pois latexmath:[$(-1)^2-4(-1)-5= 0$] e latexmath:[$(5)^2-4(5)-5= 0$];
.. Porém, o número real latexmath:[$4$] não é uma raiz, pois latexmath:[$(4)^2-4(4)-5=-5\neq 0$]. 
============================

////
[NOTE]
Para resolver uma equação é necessário por em evidência, de alguma forma, a variável, ou incógnita, da equação.


[options="unbreakable"]
.Resolvamos as seguintes equações
====
.. latexmath:[$5x+6=8$].
Solução::
latexmath:[$5x+6=8$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$5x=8-6=2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$x=\dfrac{2}{5}$]. Portanto, latexmath:[$\dfrac{2}{5}$] é a  raiz de latexmath:[$5x+6=8$].

.. latexmath:[$5x+5=1-3x$].
Solução::
latexmath:[$5x+5=1-3x$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$5x+3x=1-5$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$8x=-4$]  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=-\dfrac{4}{8}$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=-\dfrac{1}{2}$]. Portanto,  latexmath:[$-\dfrac{1}{2}$] é a  raiz de latexmath:[$5x+5=1-3x$] 

.. latexmath:[$x^2+1=0$].
Solução::  latexmath:[$x^2+1=0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$x^2=-1$]. Portanto, do item b do *Importante* posterior ao *Teorema 1.3*, para latexmath:[$b=-1$, podemos concluir que $x^2+1=0$] não tem solução em latexmath:[$\mathbb{R}$].

.. latexmath:[$4x^2-x-3=0$].
Solução::
+
--
Método 1 (Fatorando):::
latexmath:[$4x^2-x-3=0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$(4x+3)(x-1)=0$]. Pelo item (x) do *Teorema 1.1* para  latexmath:[$a=4x+3$ e $b=x-1$, temos que $(4x+3)(x-1)=0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$4x+3=0$] ou latexmath:[$x-1=0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  
latexmath:[$x=-\dfrac{3}{4}$] ou latexmath:[$x=1$]. 

Método 2 (Completando quadrados):::
latexmath:[$4x^2-x-3=0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$(2x)^2-x +\left(-\dfrac{1}{4}\right)^2-3=\left(-\dfrac{1}{4}\right)^2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$(2x)^2-x +\left(-\dfrac{1}{4}\right)^2=\dfrac{49}{16}$]
 latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$\left(2x-\dfrac{1}{4}\right)^2=\dfrac{49}{16}$] 
latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$2x-\dfrac{1}{4}=-\dfrac{7}{4}$] ou latexmath:[$2x-\dfrac{1}{4}=\dfrac{7}{4}$] 
latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$2x=-\dfrac{3}{2}$] ou
 latexmath:[$2x=2$]  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=-\dfrac{3}{4}$] ou latexmath:[$x=1$].

Método 3 (Usando a fórmula de Bhaskara ou o Discriminante latexmath:[$\Delta$]):::
Dada a equação latexmath:[$4x^2-x-3=0$], temos que  latexmath:[$\Delta=(-1)^2-4(4)(-3)=49$] e latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=\dfrac{-(-1)\pm\sqrt{\Delta}}{2(4)}$].   Então, latexmath:[$x=\dfrac{1\pm\sqrt{49}}{8}$]  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=\dfrac{1\pm 7}{8}$]  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$x=\dfrac{8}{8}$] ou latexmath:[$x=-\dfrac{6}{8}$] 
latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x=1$] ou latexmath:[$x=-\dfrac{3}{4}$]. 
--
+
Portanto, latexmath:[$-\dfrac{3}{4}$] e latexmath:[$1$] são as raízes de latexmath:[$4x^2-x-3=0$].
====



[[desigualde-subsection]]
=== Desigualdades e Intervalos


Definição 1.5:: 
Dados latexmath:[$a$] e latexmath:[$b \in \mathbb{R}$], com latexmath:[$a<b$]. Um *((intervalo))* é um  subconjunto de latexmath:[$\mathbb{R}$] e podem ser classificado em:

((Intervalos Limitados)):::	
. ((Intervalo Aberto)): latexmath:[$(a,b)=\{x \in \mathbb{R}: a<x<b\}$]
+
image::images/{cap}/IA.eps[scaledwidth="40%"]

. ((Intervalo Fechado)): latexmath:[$[a,b\]=\{x \in \mathbb{R}: a\leq x\leq b\} $]
+
image::images/{cap}/IF.eps[scaledwidth="40%"]

. Intervalo Semiaberto pela Direita: latexmath:[$[a,b)=\{x \in \mathbb{R}: a\leq x<b\}$]
+
image::images/{cap}/ISAD.eps[scaledwidth="40%"]

. Intervalo Semiaberto pela Esquerda: latexmath:[$(a,b\]=\{x \in \mathbb{R}: a< x\leq b\}$]
+
image::images/{cap}/ISAE.eps[scaledwidth="40%"]

((Intervalos Ilimitados))	:::
. ((Intervalo Aberto)):
... latexmath:[$(a,+\infty)=\{x \in \mathbb{R}: a<x\}$] 
+
image::images/{cap}/AInfty.eps[scaledwidth="40%"] 
	
... latexmath:[$(-\infty,a)=\{x \in \mathbb{R}: x<a\}$]
+
image::images/{cap}/InftyA.eps[scaledwidth="40%"]

. ((Intervalo Fechado)):
... latexmath:[$[a,+\infty)=\{x \in \mathbb{R}: a\leq x\}$]
+
image::images/{cap}/FInfty.eps[scaledwidth="40%"]

... latexmath:[$(-\infty,a\]=\{x \in \mathbb{R}: x\leq a\}$]
+
image::images/{cap}/InftyF.eps[scaledwidth="40%"]

. A Reta Real: latexmath:[$(-\infty,+\infty)=\mathbb{R}$]
+
image::images/{cap}/InftyInfty.eps[scaledwidth="40%"] 


NOTE: Os intervalos semiabertos latexmath:[$[a,b)$] e latexmath:[$(a,b\]$] também podem ser referenciados como intervalos semifechados pela esquerda e pela direita, respectivamente.

////

.{zwsp}
====
Dados os intervalos:

latexmath:[$A=[-5,2\]$], latexmath:[$B=(-2,3\]$] e latexmath:[$C=(2,6)$],

image::images/{cap}/intervalos.eps[scaledwidth="40%"]

temos que:

.. latexmath:[$A\cap B=[-2,2\]$] 
+
image::images/{cap}/intervalos_intersecao1.eps[scaledwidth="40%"]

.. latexmath:[$A\cap C=\emptyset$]

.. latexmath:[$B\cap C=(2,3\]$]
+
image::images/{cap}/intervalos_intersecao2.eps[scaledwidth="40%"]

.. latexmath:[$A\cup B=[-5,3\] $]
+
image::images/{cap}/intervalos_uniao1.eps[scaledwidth="40%"]

.. latexmath:[$A\cup C=[-5,6)$]
+
image::images/{cap}/intervalos_uniao2.eps[scaledwidth="40%"]

.. latexmath:[$B\cup C=(-2,6)$]
+
image::images/{cap}/intervalos_uniao3.eps[scaledwidth="40%"]
====



[[Inequacao]]
=== Inequações

Definição 1.6:: Uma *((inequação))* é uma afirmação que se estabelece entre duas expressões algébricas mediante uma desigualdade.

// que contém alguma das relações latexmath:[$<,\,\,\leq,\,\,>,\,\,\geq$]. 

.Tipos de Inequações
===========================
* Inequação de Primeiro grau
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[3x-4\leq 2-x\]
++++++++++++++++++++++++++++++++++++++++++++

* Inequação de Segundo grau
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[ x^2-4x -5<0 \]
++++++++++++++++++++++++++++++++++++++++++++

* Inequação Racional
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\frac{x^2-5x+4}{x^2-4}\geq x+2\]
++++++++++++++++++++++++++++++++++++++++++++
* Inequação Irracional
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\sqrt{x+3}+\sqrt{x+4}>-3\]
++++++++++++++++++++++++++++++++++++++++++++
* Inequação Exponencial
+
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[\sqrt[3]{3^{(5x+1)/3}}<\sqrt{9^{3(x+1)/5}}\]
++++++++++++++++++++++++++++++++++++++++++++
============================

Definição 1.7:: Diz-se que um número real latexmath:[$a$]  é *solução da inequação*, ou *satisfaz uma inequação*, se ao substituir a variável 
da expressão por latexmath:[$a$], a desigualdade se faz verdadeira. 


.{zwsp}
============================
Seja a inequação
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[ x^2-4x -5<0 \]
++++++++++++++++++++++++++++++++++++++++++++
Então:

.. O número real latexmath:[$4$] é uma solução da inequação de segundo grau acima, pois latexmath:[$(4)^2-4(4)-5=-5< 0$];
.. Porém, os números reais latexmath:[$-1$] e  latexmath:[$5$] não são soluções, pois latexmath:[$(-1)^2-4(-1)-5= 0\not < 0$] e latexmath:[$(5)^2-4(5)-5= 0\not < 0$];
============================

Definição 1.8:: O conjunto de todas as soluções de  uma inequação é chamado de *conjunto solução*, denotado por  latexmath:[$C.\,\,S.$] Resolver uma inequação significa encontrar seu  latexmath:[$C.\,\,S.$].

NOTE: Se não existem soluções reais para a inequação, então diz-se que  latexmath:[$C.\,\,S.$] é vazio, e se escreve, latexmath:[$C.\,\,S.=\emptyset$]


==== Resolvendo Inequações

===== Inequação de Primeiro Grau

As inequações de primeiro grau numa variável são da forma:
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[
ax+b>0 \quad \mbox{ou}\quad ax+b<0 \quad \mbox{ou}\quad ax+b\geq 0 \quad \mbox{ou}\quad ax+b\leq 0,  \quad \mbox{com}\quad a\neq 0.
\]
++++++++++++++++++++++++++++++++++++++++++++
Então, para resolver estas inequações  consideramos, sem perda de generalidade que, latexmath:[$a>0$]. Assim,

* latexmath:[ax+b>0 \quad \equiv x>-\frac{b}{a} \quad \Rightarrow \quad  C.\,\,S.=\left(-\frac{b}{a}, + \infty\right)$];

* latexmath:[ax+b<0 \quad \equiv x<-\frac{b}{a} \quad \Rightarrow \quad  C.\,\,S.=\left(-\infty, -\frac{b}{a}\right)$];

* latexmath:[ax+b\geq 0 \quad \equiv x\geq-\frac{b}{a} \quad \Rightarrow \quad  C.\,\,S.=\left[-\frac{b}{a}, + \infty\right)$];

* latexmath:[ax+b\leq 0 \quad \equiv x\leq-\frac{b}{a} \quad \Rightarrow \quad  C.\,\,S.=\left(-\infty, -\frac{b}{a}\right\]$].




.{zwsp}
====
Resolvamos as seguintes inequações de primeiro grau:

.. latexmath:[$5x+6<8$].
Solução::
latexmath:[$5x+6<8$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$5x<8-6=2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$x<\dfrac{2}{5}$]. Portanto, latexmath:[$C.\,\,S.=\left(-\infty,\dfrac{2}{5}\right)$]. 

.. latexmath:[$5x+5 \geq 1-3x$].
Solução::
latexmath:[$5x+5\geq 1-3x$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$5x+3x\geq 1-5$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$8x\geq -4$]  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x\geq -\dfrac{4}{8}=-\dfrac{1}{2}$]. +
Portanto, latexmath:[$C.\,\,S.=\left[-\dfrac{1}{2},+\infty\right)$].

.. latexmath:[$3x-4<2+x$].

Solução::  latexmath:[$3x-4<2+x$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$3x-x<2+4$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$2x<6$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x<3$]. 
Portanto, latexmath:[$C.\,\,S.=(-\infty,3)$].
====

===== Inequação de Segundo Grau

As inequações de segundo grau numa variável são da forma:
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[
ax^2+bx+c>0 \quad \mbox{ou}\quad ax^2+bx+c<0 \quad \mbox{ou}\quad ax^2+bx+c \geq 0 \quad \mbox{ou}\quad ax^2+bx+c\leq 0,  \quad \mbox{com}\quad a\neq 0.
\]
++++++++++++++++++++++++++++++++++++++++++++
Suponhamos, sem perda de generalidade, que latexmath:[$a>0$]. Antes de mostrar como resolver este tipo de inequação, devemos lembrar que a *fórmula de Bhaskara*:
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[
\mbox{Se} \quad ax^2+bx+c=0, \quad \mbox{então}\quad x=\dfrac{-b\pm\sqrt{\Delta}}{2a},
\]
++++++++++++++++++++++++++++++++++++++++++++
onde latexmath:[$\Delta=b^2-4a c$] é conhecido como o *discriminante*. Assim:

* Se latexmath:[$\Delta<0$],  então esta equação não tem raízes em latexmath:[$\mathbb{R}$];
* Se latexmath:[$\Delta\geq 0$],  então esta equação terá as seguintes raízes latexmath:[$r_1=\dfrac{-b-\sqrt{\Delta}}{2a}$] ou latexmath:[$r_2=\dfrac{-b+\sqrt{\Delta}}{2a}$] em latexmath:[$\mathbb{R}$]. Denotemos a cada uma destas raízes por latexmath:[$r_1$] e latexmath:[$r_2$], respectivamente.

Caso I:: Se latexmath:[$ax^2+bx+c=0$] tem duas raízes diferentes, com latexmath:[$r_1< r_2$], então 
+
--
... latexmath:[$ax^2+bx+c>0$] se, e somente, latexmath:[$ C.\,\,S.= (-\infty, r_1)\cup (r_2,+\infty)$];
... latexmath:[$ax^2+bx+c<0$] se, e somente se, latexmath:[$C.\,\,S.= (r_1,r_2)$];
... latexmath:[$ax^2+bx+c\geq 0$] se, e somente se, latexmath:[$C.\,\,S.= (-\infty, r_1\]\cup [r_2,+\infty)$];
... latexmath:[$ax^2+bx+c\leq 0$] se, e somente se, latexmath:[$ C.\,\,S.= [r_1,r_2\]$].
--

Caso II:: Se latexmath:[$ax^2+bx+c=0$] tem uma única raiz, latexmath:[$r=r_1= r_2$], então 
+
--
... latexmath:[$ax^2+bx+c>0$] se, e somente, latexmath:[$ C.\,\,S.= \mathbb{R}\setminus\{r\}$];
... latexmath:[$ax^2+bx+c<0$] se, e somente se, latexmath:[$C.\,\,S.=\emptyset$];
... latexmath:[$ax^2+bx+c\geq 0$] se, e somente se, latexmath:[$C.\,\,S.= \mathbb{R}$];
... latexmath:[$ax^2+bx+c\leq 0$] se, e somente se, latexmath:[$ C.\,\,S.=\{r\}$].
--

Caso III:: Se latexmath:[$ax^2+bx+c=0$] não tem raízes em latexmath:[$\mathbb{R}$],  então 
+
--
... latexmath:[$ax^2+bx+c>0$] se, e somente,  latexmath:[$C.\,\,S.= \mathbb{R}$];
... latexmath:[$ax^2+bx+c<0$] se, e somente se, latexmath:[$C.\,\,S.=\emptyset$];
... latexmath:[$ax^2+bx+c\geq 0$] se, e somente se, latexmath:[$C.\,\,S.=  \mathbb{R}$];
... latexmath:[$ax^2+bx+c\leq 0$] se, e somente se, latexmath:[$C.\,\,S.=\emptyset$].
--


.Resolvamos as seguintes inequações
============================
.. latexmath:[$x^2-2<3x+2$]

Solução::
+
--
latexmath:[$x^2-2<3x+2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x^2-3x-4<0$]. Logo, temos que as raízes de  latexmath:[$x^2-3x-4=0$] são latexmath:[$x=\dfrac{-(-3)\pm\sqrt{\Delta}}{2(1)}=\dfrac{3\pm\sqrt{\Delta}}{2}$], com latexmath:[$\Delta=(-3)^2-4(1)(-4)=25>0$]. Assim, latexmath:[$r_1=\dfrac{3-\sqrt{25}}{2}=\dfrac{-2}{2}=-1$]  e latexmath:[$r_2=\dfrac{3+\sqrt{25}}{2}=\dfrac{8}{2}=4$]. Aplicando o  item ii do *Caso I*, pois latexmath:[$r_1<r_2$], temos que latexmath:[$C.\,\,S.= (-1,4)$].

Embora já tenhamos encontrado o conjunto solução para a inequação dada, a seguir apresentamos métodos alternativos para determiná-lo.


Método 1 (Decompondo):::
latexmath:[$x^2-2<3x+2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x^2-3x-4<0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$(x-4)(x+1)<0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  
(latexmath:[$x-4<0$] e latexmath:[$x+1>0$])  ou (latexmath:[$x-4>0$] e latexmath:[$x+1<0$])  latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  
(latexmath:[$x<4$] e latexmath:[$x>-1$])  ou (latexmath:[$x>4$] e latexmath:[$x<-1$]) 
 latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$-1<x<4$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x \in (-1,4)$]. 

Método 2 (Completando Quadrados):::
latexmath:[$x^2-2<3x+2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x^2-3x<4$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] 
 latexmath:[$x^2-3x+\dfrac{9}{4}<4+\dfrac{9}{4}$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$\left(x-\dfrac{3}{2}\right)^2<\dfrac{25}{4}$]
 latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$-\dfrac{5}{2}<x-\dfrac{3}{2}<\dfrac{5}{2}$] 
latexmath:[$\,\,\,\Leftrightarrow\,\,\,$] latexmath:[$-1<x<4$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x \in (-1,4)$]. 

Método 3 (Encontrando o quadro de sinais):::
latexmath:[$x^2-2<3x+2$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$x^2-3x-4<0$] latexmath:[$\,\,\,\Leftrightarrow\,\,\,$]  latexmath:[$(x+1)(x-4)<0$]. 
Os valores de latexmath:[$x$] para os que latexmath:[$(x+1)(x-4)=0$] são latexmath:[$x=-1$] e latexmath:[$x=4$] (raízes de cada fator). Logo,
+
.Quadro de sinais
image::images/{cap}/pc1.eps[scaledwidth="50%"]
+
Na Figura 1.3 observamos que latexmath:[$(x+1)(x-4)<0$],  se latexmath:[$x \in (-1,4)$].
--
+
Portanto, latexmath:[$C.\,\,S.=(-1,4)$].


.. latexmath:[$x^2+1<0$]

Solução::  latexmath:[$x^2-1<0$]. Logo, temos que as raízes de latexmath:[$x^2+1=0$] são latexmath:[$x=\dfrac{-(0)\pm\sqrt{\Delta}}{2(1)}=\pm\dfrac{\sqrt{\Delta}}{2}$], com latexmath:[$\Delta=(0)^2-4(1)(1)=-16<0$]. Desde que, latexmath:[$\Delta=<0$], então a equação latexmath:[$x^2+1=0$] não tem raízes em latexmath:[$\mathbb{R}$]. Assim, Aplicando o  item ii do *Caso III*, temos que latexmath:[$C.\,\,S.= \emptyset$].

.. latexmath:[$4x^2-x-3\geq 0$].
Solução::
latexmath:[$4x^2-x-3\geq 0$]. Logo, temos que as raízes de latexmath:[$4x^2-x-30$] são latexmath:[$x=\dfrac{-(-1)\pm\sqrt{\Delta}}{2(4)}=\dfrac{1\pm\sqrt{\Delta}}{8}$], com latexmath:[$\Delta=(-1)^2-4(4)(-3)=49>0$]. Assim, latexmath:[$r_1=\dfrac{1-\sqrt{49}}{8}=\dfrac{-6}{8}=-\dfrac{3}{4}$]  e latexmath:[$r_2=\dfrac{1+\sqrt{49}}{8}=\dfrac{8}{8}=1$]. Aplicando o  item iii do *Caso I*, pois latexmath:[$r_1<r_2$], temos que latexmath:[$C.\,\,S.= \big(-\infty,-\frac{3}{4}\big\]\cup \big[1,+\infty\big)$].


============================



===== Inequações Polinomiais

As inequações polinomiais numa variável são da forma:
[latexmath]
++++++++++++++++++++++++++++++++++++++++++++
\[
P(x)=a_nx^n+\dots + a_1x+a_0>0 \quad \mbox{ou}\quad P(x)=a_nx^n+\dots + a_1x+a_0<0 \quad \mbox{ou}
\]
\[
P(x)=a_nx^n+\dots + a_1x+a_0 \geq 0 \quad \mbox{ou}\quad P(x)=a_nx^n+\dots + a_1x+a_0\leq 0,  
\]
++++++++++++++++++++++++++++++++++++++++++++
onde latexmath:[$a_0,\,\,a_1,\dots,a_n$] são contantes e latexmath:[$a_n> 0$], latexmath:[$n \in \mathbb{N}$].


Assim como nos casos anteriores, este tipo de inequação é resolvido de acordo com a natureza das raízes da equação polinomial latexmath:[$P(x)=0$]. Desde que este polinômio seja de grau latexmath:[$n$], então esta equação pode ter no máximo latexmath:[$n$] raízes em latexmath:[$\mathbb{R}$]. Vamos denotar cada uma destas  raízes por latexmath:[$r_1,\,\,r_2,\dots,r_n$].

Caso I:: 
Se latexmath:[$P(x)=0$] tem latexmath:[$n$] raízes diferentes em latexmath:[$\mathbb{R}$], com latexmath:[$r_1<r_2<\dots<r_{n-1}<r_n$],  então alternamos o sinal latexmath:[$+$]  e latexmath:[$-$] nos intervalos consecutivos determinados por elas raízes, começamos assinando o sinal latexmath:[$+$] ao intervalo mais a direita, isto é, aquele que contém a raiz  latexmath:[$r_n$], veja a figura a seguir:
+
image::images/{cap}/raizes_polinomio.eps[scaledwidth="80%"]
+
Logo, 

... latexmath:[$P(x)>0$]  se, e somente, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$+$], isto é:
+
--
.. Se  latexmath:[$ n$] é par, então  latexmath:[$C.\,\,S.= (-\infty, r_1)\cup \dots\cup (r_n,+\infty)$];
.. Se  latexmath:[$ n$] é í
ímpar, então  latexmath:[$C.\,\,S.= ( r_1,r_2)\cup \dots\cup (r_n,+\infty)$];
--
+
... latexmath:[$P(x)<0$] se, e somente se, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$-$], isto é:
+
--
.. Se  latexmath:[$ n$] é par, então  latexmath:[$C.\,\,S.= (r_1,r_2)\cup \dots\cup (r_{n-1},r_n)$];
.. Se  latexmath:[$ n$] é ímpar, então  latexmath:[$C.\,\,S.=(-\infty, r_1)\cup \dots\cup (r_{n-1},r_n)$];
--
+
... latexmath:[$P(x)\geq 0$]  se, e somente, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$+$], isto é:
+
--
.. Se  latexmath:[$ n$] é par, então  latexmath:[$C.\,\,S.= (-\infty, r_1\]\cup \dots\cup [r_n,+\infty)$];
.. Se  latexmath:[$ n$] é ímpar, então  latexmath:[$C.\,\,S.= [ r_1,r_2\]\cup \dots\cup [r_n,+\infty)$];
--
+
... latexmath:[$P(x)\leq 0$] se, e somente se, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$-$], isto é:
+
--
.. Se  latexmath:[$ n$] é par, então  latexmath:[$C.\,\,S.= [r_1,r_2\]\cup \dots\cup [r_{n-1},r_n\]$];
.. Se  latexmath:[$ n$] é ímpar, então  latexmath:[$C.\,\,S.=(-\infty, r_1\]\cup \dots\cup [r_{n-1},r_n\]$];
--

Caso II:: Se algumas das raízes de latexmath:[$P(x)=0$] são reais de multiciplicidade de ordem maior que  latexmath:[$1$], então: 

... Se a multiciplicidade de uma das raízes é par, então esta raiz não será considerada para a determinação dos intervalos e o latexmath:[$C.\,\,S.$] será obtido com o mesmo procedimento do *Caso I*;

... Se a multiciplicidade de uma das raízes é ímpar, então esta raiz é considerada para a determinação dos intervalos e o latexmath:[$C.\,\,S.$] será obtido com o mesmo procedimento do *Caso I*.

Caso III:: Se algumas das raízes de latexmath:[$P(x)=0$] não são reais, então elas não são consideradas na determinação dos intervalos. Em outras palavras, o latexmath:[$C.\,\,S.$] será obtido  seguindo os procedimentos dos casos anteriores com as raízes reais.

.Resolvamos as seguintes inequações
====
.. latexmath:[$(x-1)^4(x+2)(x+4)\leq 0$]
Solução::
Resolvendo a equação latexmath:[$(x-1)^4(x+2)(x+4)=0$], temos que latexmath:[$r_1=-4$], latexmath:[$r_2=-2$] e latexmath:[$r_3=1$], com multiciplicidade latexmath:[$4$]. Como a inequação é da forma latexmath:[$P(x)\leq 0$], podemos aplicar o item i do *Caso II* e   o item iv(a) do *Caso I*, pois, somente consideraremos as raízes latexmath:[$r_1=-4$], latexmath:[$r_2=-2$]. Ou seja, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$(-)$]. Veja a figura a seguir:
+
image::images/{cap}/raizes_polinomio1.eps[scaledwidth="50%"]
+
Em outras palavras,  
+
[latexmath]
++++
\[
C.S.=[-4,-2].
\]
++++ 

.. latexmath:[$(x^2-3)^5(x^2+16)(x^2-16)(x^4+1)> 0$]
Solução::
Resolvendo a equação latexmath:[$(x^2-3)^5(x^2+16)(x^2-16)(x^4+1)=0$], temos que latexmath:[$r_1=-4$], latexmath:[$r_2=-\sqrt{3}$],  latexmath:[$r_3=\sqrt{3}$], com multiciplicidade latexmath:[$5$] cada, e  latexmath:[$r_4=4$]. Note que latexmath:[$x^4+1= 0$] e latexmath:[$x^2+16= 0$] não têm raízes reais, logo, as expressões latexmath:[$x^4+1$] e latexmath:[$x^2+16$] não serão consideradas.  Como a inequação é da forma latexmath:[$P(x)> 0$], podemos aplicar o item ii do *Caso II* e   o item i(a) do *Caso I*, pois,  consideraremos todas as raízes  latexmath:[$r_1=-4$], latexmath:[$r_2=-\sqrt{3}$],  latexmath:[$r_3=\sqrt{3}$] e latexmath:[$r_4=4$]. Ou seja, então latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$(+)$]. Veja figura a seguir:
+
image::images/{cap}/raizes_polinomio2.eps[scaledwidth="70%"]
+
Em outras palavras,  
+
[latexmath]
++++
\[
C.S.=(-\infty, -4)\cup (-\sqrt{3},\sqrt{3})\cup (4,+\infty).
\]
++++ 
====


===== Inequação Racional

As inequações racionais numa variável são da forma:
[latexmath]
++++
\[
\dfrac{P(x)}{Q(x)}>0 \quad \mbox{ou}\quad \dfrac{P(x)}{Q(x)}<0 \quad \mbox{ou}\quad \dfrac{P(x)}{Q(x)}\geq0 \quad \mbox{ou}\quad \dfrac{P(x)}{Q(x)}\leq 0,
\]
++++ 
onde latexmath:[$P(x)$] e latexmath:[$Q(x)$] são polinômios diferentes de zero.

Para resolver este tipo de inequações, devemos ter em mente que elas são equivalentes a:
[latexmath]
++++
\[
P(x)Q(x)>0 \quad \mbox{ou}\quad {P(x)}{Q(x)}<0 \quad \mbox{ou}\quad {P(x)}{Q(x)}\geq0  \quad \mbox{e}\quad  \quad \mbox{ou}\quad {P(x)}{Q(x)}\leq 0,
\]
++++ 
respectivamente. Logo, para obter o conjunto solução procedemos como nos casos anteriores, sendo que quando a inequação é latexmath:[$\geq $] ou latexmath:[$\leq $], os intervalos que contêm  alguma das raízes da equação latexmath:[$Q(x)=0$] devem ser abertos nesses extremos.


.Resolvamos a seguinte inequação
====
.. latexmath:[\dfrac{x-2}{x-4}>\dfrac{x+2}{x}]

Solução:: latexmath:[\,\,]
+
[latexmath]
++++
\[
 \dfrac{x-2}{x-4}>\dfrac{x+2}{x}\quad \Leftrightarrow\quad\dfrac{x+2}{x}-\dfrac{x-2}{x-4}<0\quad \Leftrightarrow\quad\dfrac{(x+2)(x-4)-x(x-2)}{x(x-4)}<0
\]
\[
  \Leftrightarrow\quad\dfrac{-8}{x(x-4)}<0\quad \Leftrightarrow\quad\dfrac{1}{x(x-4)}>0\quad \Leftrightarrow\quad{x(x-4)}>0.
\]
++++ 
+
Assim, as raízes dos fatores são latexmath:[$r_1=0$] e latexmath:[$r_2=4$]. Como a inequação é da forma latexmath:[$P(x)> 0$],  podemos aplicar o item i(a) do *caso I*, pois  consideraremos todas as raízes. Ou seja, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$(+)$], conforme a figura a seguir:
+
image::images/{cap}/raizes_polinomio4.eps[scaledwidth="50%"]
+
Logo, latexmath:[$C.\,\,S.=(-\infty,0)\cup (4,+\infty)$].

.. latexmath:[\dfrac{x(x+2)}{x-1}+ \dfrac{(x-1)(x+2)}{x}\leq \dfrac{2x(x+2)}{x+1}]

Solução::
latexmath:[\,\,]
+
[latexmath]
++++
\[
\dfrac{x(x+2)}{x-1}+ \dfrac{(x-1)(x+2)}{x}\leq \dfrac{2x(x+2)}{x+1} \quad \Leftrightarrow\quad\dfrac{x(x+2)}{x-1}+ \dfrac{(x-1)(x+2)}{x}- \dfrac{2x(x+2)}{x+1}\leq 0 
\]
\[
   \Leftrightarrow\quad\dfrac{(x^2(x+1)+(x-1)(x-1)(x+1)-2x^2(x-1))(x+2)}{(x-1)x(x+1)}\leq 0  \quad \Leftrightarrow \]
\[
\dfrac{(2x^2-x+1)(x+2)}{(x-1)x(x+1)}\leq 0\quad \Leftrightarrow\quad {(2x^2-x+1)(x+2)}{(x-1)x(x+1)}\leq 0,
\]
++++ 
+
com latexmath:[$x\neq-1, 0,1$]. Assim, as raízes dos fatores são latexmath:[$r_1=-2$], latexmath:[$r_2=-1$], latexmath:[$r_3=0$] e 
latexmath:[$r_4=1$]. Note que latexmath:[$2x^2-x+1=0$]  não tem raízes reais, logo a expressão  latexmath:[$2x^2-x+1$] não será considerada. Como a inequação é da forma latexmath:[$P(x)\leq 0$],  podemos aplicar o item iii(a) do *caso I*, pois  consideraremos todas as raízes. Ou seja, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$(-)$], veja figura a seguir:
+
image::images/{cap}/raizes_polinomio3.eps[scaledwidth="80%"]
+
Logo, latexmath:[$C.\,\,S.=[-2,-1)\cup (0,1)$].

====


===== Inequações Exponenciais
As inequações exponenciais numa variável são da forma:
[latexmath]
++++
\[
a^{f(x)}> a^{g(x)}\quad \mbox{ou}\quad a^{f(x)}< a^{g(x)}\quad \mbox{ou}\quad a^{f(x)}\geq  a^{g(x)}\quad \mbox{ou}\quad a^{f(x)}\leq a^{g(x)},
\]
++++
onde latexmath:[$f(x)$] e latexmath:[$g(x)$] são expressões em latexmath:[$x$], latexmath:[$a >0$], latexmath:[$a\neq 1$].


Para resolver este tipo de inequação, são considerados dois casos.

Caso I::
Se latexmath:[$a>1$], então os expoentes da inequação  preservam a mesma ordem, isto é:  

... latexmath:[$a^{f(x)}> a^{g(x)}$] se, e somente se, latexmath:[${f(x)}>{g(x)}$];
... latexmath:[$a^{f(x)}< a^{g(x)}$] se, e somente se, latexmath:[${f(x)}<{g(x)}$];
... latexmath:[$a^{f(x)}\geq  a^{g(x)}$] se, e somente se, latexmath:[${f(x)}\geq {g(x)}$];
... latexmath:[$a^{f(x)}\leq a^{g(x)}$] se, e somente se, latexmath:[${f(x)}\leq {g(x)}$].


Caso II::
Se latexmath:[$0<a<1$], então os expoentes da inequação invertem  a ordem, isto é:  

... latexmath:[$a^{f(x)}> a^{g(x)}$] se, e somente se, latexmath:[${f(x)}<{g(x)}$];
... latexmath:[$a^{f(x)}< a^{g(x)}$] se, e somente se, latexmath:[${f(x)}>{g(x)}$];
... latexmath:[$a^{f(x)}\geq  a^{g(x)}$] se, e somente se, latexmath:[${f(x)}\leq {g(x)}$];
... latexmath:[$a^{f(x)}\leq a^{g(x)}$] se, e somente se, latexmath:[${f(x)}\geq{g(x)}$].

Logo, o conjunto solução  de cada item é obtido resolvendo esta última inequação, usando os procedimentos vistos nos casos anteriormente.


.Resolver as seguintes inequações
====
.. latexmath:[$2^{(5x+2)/4}> \sqrt[4\]{2^{4(x+1)/5}}$] 

Solução:: 
latexmath:[$\,$]
+
[latexmath]
++++
\[
2^{(5x+2)/4}> \sqrt[4]{2^{4(x+1)/5}}\quad \Leftrightarrow \quad 
2^{(5x+2)/4}> 2^{4(x+1)/(4\cdot 5)}\quad \Leftrightarrow \quad 
2^{(5x+2)/4}> 2^{(x+1)/5} 
\]
++++
+
Como a inequação é da forma latexmath:[$a^{f(x)}>a^{g(x)}$], com  latexmath:[$a=2>1$],  podemos aplicar o item i do *caso I*, isto é
+
[latexmath]
++++
\[
2^{(5x+2)/4}> 2^{(x+1)/5}\quad \Leftrightarrow\quad \dfrac{5x+2}{4}> \dfrac{x+1}{5}\quad \Leftrightarrow 
\]
\[ 
\dfrac{5x+2}{4}- \dfrac{x+1}{5}>0\quad \Leftrightarrow \quad 
\dfrac{5(5x+2)-4(x+1)}{20}\quad \Leftrightarrow 
\]
\[
\dfrac{21x+6}{20}>0\quad \Leftrightarrow \quad \dfrac{3(7x+2)}{20}>0\quad \Leftrightarrow \quad {7x+2}>0\quad \Leftrightarrow \quad x>-\dfrac{2}{7}.
\]
++++
+
Portanto,  latexmath:[$C.S.=\big(-\frac{2}{7},+\infty\big)$].





.. latexmath:[$\left((0,3)^{(3x+2)(x+1)}\right)^\frac{1}{x+2}\geq \dfrac{(0,9)^{2x+5}}{3^{2x+5}}$] 


Solução::
latexmath:[$\,$]
+
[latexmath]
++++
\[
\left((0,3)^{(3x+2)(x+1)}\right)^\frac{1}{x+2}\geq \dfrac{(0,9)^{2x+5}}{3^{2x+5}}\quad \Leftrightarrow 
\quad 
(0,3)^{\frac{(3x+2)(x+1)}{x+2}}\geq {\left(\frac{0,9}{3}\right)}^{2x+5}
\]
\[\quad \Leftrightarrow \quad 
(0,3)^{\frac{(3x+2)(x+1)}{x+2}}\geq (0,3)^{2x+5}.
\]
++++
+
Como a inequação é da forma latexmath:[$a^{f(x)}>a^{g(x)}$], com  latexmath:[$a=0,3<1$],  podemos aplicar o item iv do *caso II*, isto é
+
[latexmath]
++++
\[
 (0,3)^{\frac{(3x+2)(x+1)}{x+2}}\geq (0,3)^{2x+5}
\quad \Leftrightarrow \quad \dfrac{(3x+2)(x+1)}{x+2}\leq {2x+5}\quad \Leftrightarrow  
\]
\[
 \dfrac{(3x+2)(x+1)}{x+2}-{2x+5}\leq  0
\quad \Leftrightarrow \quad \dfrac{(3x+2)(x+1)-(2x+5)(x+2)}{x+2}\leq  0
\quad \Leftrightarrow 
\]
\[
\dfrac{x^2-4x-8}{x+2}\leq  0\quad \Leftrightarrow \quad 
\dfrac{(x-2-2\sqrt{3})(x-2+2\sqrt{3})}{x+2}\leq  0
\quad \Leftrightarrow 
\]
\[
{(x-2-2\sqrt{3})(x-2+2\sqrt{3})}{(x+2)}\leq  0, \quad \mbox{com }\quad x\neq -2.
\]
++++
+
Como a inequação é da forma latexmath:[$P(x)\leq 0$], podemos aplicar o item iv(b) do *Caso I*. Ou seja, latexmath:[$x$] pertence à união dos intervalos com sinal latexmath:[$(-)$], veja figura a seguir:
+
image::images/{cap}/raizes_polinomio5.eps[scaledwidth="60%"]
+
Logo, latexmath:[$C.\,\,S.=(-\infty,-2)\cup [2-2\sqrt{3},2+2\sqrt{3}\]$].
====



===== Inequações Irracionais

As inequações irracionais numa variável são da forma:
[latexmath]
++++
\[
F(x,P(x),\sqrt{Q(x)},\sqrt[3]{R(x)},\dots,\sqrt[n]{W(x)})>0\quad \mbox{ou}\quad F(x,P(x),\sqrt{Q(x)},\sqrt[3]{R(x)},\dots,\sqrt[n]{W(x)})<0\quad \mbox{ou}
\]
\[
F(x,P(x),\sqrt{Q(x)},\sqrt[3]{R(x)},\dots,\sqrt[n]{W(x)})\geq 0\quad \mbox{ou}\quad F(x,P(x),\sqrt{Q(x)},\sqrt[3]{R(x)},\dots,\sqrt[n]{W(x)})\leq 0,
\]
++++
onde latexmath:[$P(x),\,\,Q(x),\dots,W(x)$] são polinômios. 

Casos Particulares:: latexmath:[$\,$]

Caso I::: Para as inequações da forma:
... latexmath:[$\sqrt{P(x)}>Q(x)$] latexmath:[$ \quad \Leftrightarrow\quad$] latexmath:[$P(x)\geq 0$] e  latexmath:[$(Q(x)\leq 0\,\,\mbox{ou}\,\,  P(x)>Q^2(x))$]; 
... latexmath:[$\sqrt{P(x)}\geq Q(x)$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0$] e  latexmath:[$(Q(x)\leq 0\,\,\mbox{ou}\,\,  P(x) \geq Q^2(x))$]; 

... latexmath:[$\sqrt{P(x)}<Q(x)$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0$] e  latexmath:[$Q(x)> 0$] e latexmath:[$ P(x)<Q^2(x)$]; 
... latexmath:[$\sqrt{P(x)}\leq Q(x)$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0$] e  latexmath:[$Q(x)\geq 0$] e latexmath:[$P(x) \leq Q^2(x)$].

Caso II::: Para as inequações da forma:

... latexmath:[$\sqrt{P(x)}+ \sqrt{Q(x)}>0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$(P(x)\geq 0\,\,\mbox{e}\,\,  Q(x)> 0)$]  ou latexmath:[$(P(x)> 0\,\,\mbox{e}\,\,  Q(x)\geq 0)$];
... latexmath:[$\sqrt{P(x)}+ \sqrt{Q(x)}\geq 0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0\,\,\mbox{e}\,\,  Q(x)\geq 0$];

... latexmath:[$\sqrt{P(x)}\pm \sqrt{Q(x)}\geq k$], latexmath:[$k > 0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0\,\,\mbox{e}\,\,  Q(x)\geq 0 \,\,\mbox{e}\,\, P(x)\geq (k\mp\sqrt{Q(x)})^2$];

... latexmath:[$\sqrt{P(x)}+ \sqrt{Q(x)}<0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$C.S.=\emptyset$];
... latexmath:[$\sqrt{P(x)}+ \sqrt{Q(x)}\leq 0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)= 0\,\,\mbox{e}\,\,  Q(x)= 0$].

Caso III::: Para as inequações da forma:

... latexmath:[$\sqrt{P(x)}- \sqrt{Q(x)}>0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0\,\,\mbox{e}\,\,  Q(x)\geq  0$]  e latexmath:[$P(x)>  Q(x)$];
... latexmath:[$\sqrt{P(x)}- \sqrt{Q(x)}\geq 0$]latexmath:[$ \quad \Leftrightarrow\quad$]latexmath:[$P(x)\geq 0\,\,\mbox{e}\,\,  Q(x)\geq 0$]   e latexmath:[$P(x)\geq   Q(x)$].



.Resolvamos as seguintes inequações
====
..  latexmath:[$\sqrt{x^2-x-2}<5-x$]
Solução:: 
 
Aplicando o item iii do *Caso I*, para latexmath:[$P(x)=x^2-x-2$] e latexmath:[$Q(x)=5-x$], temos que: 
+
[latexmath]
++++
\[
\sqrt{x^2-x-2}<5-x \quad \Leftrightarrow \quad {x^2-x-2}\geq 0 \quad \mbox{e}\quad 5-x \geq 0  \quad \mbox{e} \quad x^2-x-2<(5-x)^2
\]
\[
\quad \Leftrightarrow \quad (x-2)(x+1)\geq 0\quad \mbox{e}\quad 5 \geq x  \quad \mbox{e} \quad x^2-x-2<25-10x+ x^2
\]
\[
\quad \Leftrightarrow \quad  x \in (-\infty, -1]\cup[2,+\infty)\quad \mbox{e}\quad  x \in (-\infty, 5]  \quad \mbox{e} \quad 9x<27 
\]
\[
 \quad \Leftrightarrow \quad x \in (-\infty, -1]\cup[2, 5]  \quad \mbox{e} \quad x \in (-\infty,3) \quad \Leftrightarrow \quad x \in (-\infty, -1]\cup[2, 3).
\]
++++
+
Portanto, latexmath:[$C.S.=(-\infty, -1\]\cup[2, 3)$].


..  latexmath:[$\sqrt{x-8}\leq 0$]
Solução:: 
 
Aplicando o item iv do *Caso I*, para latexmath:[$P(x)=x-8$] e latexmath:[$Q(x)=0$],  temos que:
+
[latexmath]
++++
\[
\sqrt{x-8}\leq 0\quad \Leftrightarrow \quad x-8 \geq 0 \quad \mbox{e} \quad 0\leq 0  \quad \mbox{e} \quad x-8\leq 0^2=0
\]
\[
\quad \Leftrightarrow \quad x\geq 8 \quad \mbox{e} \quad x\leq 8 \quad \Leftrightarrow \quad x=8.
\]
++++
+
Portanto, latexmath:[$C.S.=\{8\}$].

..  latexmath:[$\sqrt{x+5}<0$]
Solução:: 
Aplicando o item iii do *Caso I*, para latexmath:[$P(x)=x+5$] e latexmath:[$Q(x)=0$],  temos que:
+
[latexmath]
++++
\[
\sqrt{x+5}< 0\quad \Leftrightarrow \quad x+5 \geq 0 \quad \mbox{e} \quad 0> 0  \quad \mbox{e} \quad x+5< 0^2=0
\]
\[
\quad \Leftrightarrow \quad x\geq -5 \quad \mbox{e} \quad 0> 0  \quad \mbox{e} \quad x\leq -5 \quad \Leftrightarrow \quad  \emptyset.
\]
++++
+
Portanto, latexmath:[$C.S.=\emptyset$]. +
Note que não é necessário fazer as contas acima para obter latexmath:[$C.S.=\emptyset$], pois  latexmath:[$\sqrt{x+5}\geq 0$] da definição da raiz quadrada, logo, latexmath:[$\sqrt{x+5}< 0$] é uma inequação não válida.


====


Caso IV::: Se latexmath:[$n\geq 1$] é ímpar
...  latexmath:[$\dfrac{P(x)\sqrt[n\]{Q(x)}}{R(x)}\geq 0 $] latexmath:[$ \quad \,\Leftrightarrow \quad \,$] latexmath:[$\dfrac{P(x){Q(x)}}{R(x)}\geq 0 $];

...  latexmath:[$\dfrac{P(x)\sqrt[n\]{Q(x)}}{R(x)}\leq 0 $]latexmath:[$ \quad \,\Leftrightarrow \quad \,$] latexmath:[$\dfrac{P(x){Q(x)}}{R(x)}\leq 0 $];

...  latexmath:[$\dfrac{P(x)}{R(x)\sqrt[n\]{Q(x)}}\geq 0 $]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$\dfrac{P(x)}{R(x){Q(x)}}\geq 0 $];

...  latexmath:[$\dfrac{P(x)}{R(x)\sqrt[n\]{Q(x)}}\leq 0 $]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$\dfrac{P(x)}{R(x){Q(x)}}\leq 0 $];

... latexmath:[$\sqrt[n\]{P(x)}\leq \sqrt[n\]{Q(x)}$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$P(x)\leq   Q(x)$].  

[NOTE]
Se  a desigualdade a ser analisada é estrita, isto é,  latexmath:[$>$ ou $<$], então na  sua  inequação equivalente subtituímos latexmath:[$\geq $ ou $\leq $] por latexmath:[$>$ ou $<$], respectivamente.

Caso V::: Se latexmath:[$n>0$] é par

...  latexmath:[${P(x)\sqrt[n\]{Q(x)}}\geq 0$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$] latexmath:[$P(x)\geq 0 \quad \mbox{e}  \quad {Q(x)}\geq 0$];

...  latexmath:[${P(x)\sqrt[n\]{Q(x)}}\leq 0$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$] latexmath:[$P(x)\leq 0 \quad \mbox{e}  \quad {Q(x)}\geq 0$];

...  latexmath:[$\dfrac{P(x)}{R(x)\sqrt[n\]{Q(x)}}\geq 0$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$Q(x)>0 \quad \mbox{e} \quad \dfrac{P(x)}{R(x)}\geq 0$];

...  latexmath:[$\dfrac{P(x)}{R(x)\sqrt[n\]{Q(x)}}\leq 0$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$Q(x)>0 \quad \mbox{e} \quad \dfrac{P(x)}{R(x)}\leq 0$];

...  latexmath:[$\sqrt[n\]{P(x)}\geq Q(x)$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$P(x)\geq 0 \quad \mbox{e} \quad (Q(x)\leq 0 \quad \mbox{ou} \quad  P(x)\geq Q^n(x))$];

... latexmath:[$\sqrt[n\]{P(x)}\leq Q(x)$]latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$P(x)\geq 0 \quad \mbox{e} \quad Q(x)\geq 0 \quad \mbox{e} \quad  P(x)\leq Q^n(x)$];


... latexmath:[$\sqrt[n\]{P(x)}\leq \sqrt[n\]{Q(x)}$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$]latexmath:[$P(x)\geq 0 \quad \mbox{e} \quad Q(x)\geq 0 \quad \mbox{e} \quad P(x)\leq   Q(x)$].  

[NOTE]
Se a desigualdade a ser analisada é estrita, isto é,  latexmath:[$>$ ou $<$], então na  sua  inequação equivalente subtituímos latexmath:[$\geq $ ou $\leq $] por latexmath:[$>$ ou $<$], nas inequações que envolvam latexmath:[$P(x)$,  $Q(x)$ e $R(x)$], respectivamente.


.Resolvamos as seguintes inequações
====
.. latexmath:[$\dfrac{x+5}{(x-4)\sqrt[7\]{81-x^2}}\leq 0$]

Solução:: Aplicando o item ii do *Caso IV*, para latexmath:[$P(x)=x+5$, $Q(x)=\sqrt[7\]{81-x^2}$ e $R(x)=x-4$], temos que:
+
[latexmath]
++++
\[
\dfrac{x+5}{(x-4)\sqrt[7]{81-x^2}}\leq 0\quad \Leftrightarrow\quad  \dfrac{x+5}{(x-4)(81-x^2)}\leq 0\quad \Leftrightarrow
\]
\[
 \dfrac{x+5}{(x-4)(9-x)(9+x)}\leq 0\quad \Leftrightarrow\quad 
-\dfrac{x+5}{(x-4)(x-9)(x+9)}\leq 0\quad \Leftrightarrow
\]
\[
  \dfrac{x+5}{(x-4)(x-9)(x+9)}\geq 0
\quad \Leftrightarrow\quad   x \in(-\infty, -9)\cup [-5, 4)\cup (9,+\infty).
\]
++++
+
Portanto, latexmath:[$C.S.=(-\infty, -9)\cup [-5, 4)\cup (9,+\infty)$]

.. latexmath:[$\dfrac{x+5}{(x-4)\sqrt[6\]{81-x^2}}\geq 0$]

Solução:: Aplicando o item iii do *Caso V*, para latexmath:[$P(x)=x+5$, $Q(x)=\sqrt[6\]{81-x^2}$ e $R(x)=x-4$], temos que:
+
[latexmath]
++++
\[
\dfrac{x+5}{(x-4)\sqrt[6]{81-x^2}}\geq 0\quad \Leftrightarrow\quad  81-x^2> 0\quad\mbox{e}\quad\dfrac{x+5}{x-4}\geq 0
\quad \Leftrightarrow\]
\[
  81>x^2\quad\mbox{e}\quad ((x+5)(x-4)\geq 0\quad\mbox{com}\quad x\neq 4)
\]
\[
\quad \Leftrightarrow\quad  x \in(-9,9)\quad\mbox{e}\quad x \in (-\infty, -5]\cup (4,+\infty)
\quad \Leftrightarrow\quad  x \in(-9, -5]\cup (4,9)
\]
++++
+
Portanto, latexmath:[$C.S.=(-9, -5\]\cup (4,9)$]


====


[NOTE]
Se temos latexmath:[$k$] radicais, cada um deles terá um conjunto solução relativo, então o conjunto solução da inequação toda será a interseção destes latexmath:[$k$] conjuntos soluções.


=== Valor absoluto 

Definição 1.9:: O *((valor absoluto))* de um número real é denotado por latexmath:[$|a|$] e definido como:
+
[latexmath]
++++
\[
|a|=\left\{ 
\begin{array}{ccc}
a,  & & \mbox{se } a\geq 0\\
-a, & & \mbox{se } a < 0.
\end{array} 
\right.
\]
++++
	
Desde o ponto de vista geométrico latexmath:[$|a|$] representa a distância entre o ponto da 
reta real latexmath:[$a$] e a origem latexmath:[$0$].

image::images/{cap}/va1.eps[scaledwidth="40%"]

Da mesma forma, latexmath:[$|a-b|=|b-a|$] se interpreta como a distância entre os pontos latexmath:[$a$] e latexmath:[$b$].

image::images/{cap}/va2.eps[scaledwidth="40%"]


.{zwsp}
====

latexmath:[$|7|=7$];
latexmath:[$\quad |0|=0$]; 
latexmath:[$\quad|-4|=4$];
latexmath:[$\quad|-|a||=|a|$].
====


Teorema 1.4:: 
Se latexmath:[$a$] e latexmath:[$b \in \mathbb{R}$], então:
... latexmath:[$|a|\geq 0$], latexmath:[$\quad \forall a\in \mathbb{R}$] e latexmath:[$|a|=0$] se, e somente se, latexmath:[$ a=0$];
... latexmath:[$|ab|=|a||b|$];
... latexmath:[$|a+b|\leq |a| +|b|$].


A seguir, enunciamos outras propriedades adicionais que o *valor absoluto* verifica.


Teorema 1.5::
Se latexmath:[$a$], latexmath:[$b$] e latexmath:[$x \in \mathbb{R}$], então:
... latexmath:[$|a|^2=a^2$];
... Se latexmath:[$b\geq 0$], latexmath:[$|a|=b$] se, e somente se, latexmath:[$ a=b$] ou latexmath:[$a=-b$];
... latexmath:[$|a|=|b|$] se, e somente se, latexmath:[$ a=b$] ou latexmath:[$a=-b$];
... latexmath:[$|-a|=|a|=\sqrt{a^2}$];
... latexmath:[$\left|\dfrac{a}{b}\right|=\dfrac{|a|}{|b|}$], latexmath:[$b\neq 0$];
... Se latexmath:[$a<x<b $,  então $ |x|<\max\{|a|,|b|\}$];
+
--
.. Se latexmath:[$0<a $,  então $ a<|x|<b$];
.. Se latexmath:[$b<0 $,  então $ -b<|x|<-a$];
--
+
... Se latexmath:[$b>0$], latexmath:[$|x|<b $] se, e somente se, latexmath:[$-b<x<b$];
... Se latexmath:[$b\geq 0$], latexmath:[$|x|\leq b$] se, e somente se, latexmath:[$ -b\leq x\leq b$];
... Se latexmath:[$|x|> b $] se, e somente se, latexmath:[$x>b$] ou latexmath:[$x<-b$];
... Se latexmath:[$|x|\geq b$] se, e somente se, latexmath:[$ x\geq b$] ou latexmath:[$x\leq-b$];
... latexmath:[$||a|-|b|| \leq |a-b|\leq |a|+|b|$].




.Resolvamos as seguintes equações com valor absoluto:
====
.. latexmath:[$|3x-5|=4$].
Solução::
latexmath:[$|3x-5|=4  \quad \,\Leftrightarrow \quad \, 3x-5=4$] ou	 latexmath:[$3x-5=-4  \quad \,\Leftrightarrow \quad \, x=3$] ou latexmath:[$x=\dfrac{1}{3}$]. Portanto,  latexmath:[$\frac{1}{3}$] e latexmath:[$3$] são raízes de latexmath:[$|3x-5|=4$].

.. latexmath:[$||7-4x|-3|=9$].
Solução::
latexmath:[$||7-4x|-3|=9$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$]  latexmath:[$|7-4x|-3 =9$] ou latexmath:[$|7-4x|-3=-9$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$]  
latexmath:[$|7-4x| =12$] ou latexmath:[$|7-4x|=-6$], porém  latexmath:[$|7-4x|\geq 0$] e latexmath:[$-6<0$], isto contradiz o item(i) do *Teorema 1.4*. Então, só devemos analisar latexmath:[$|7-4x| =12$]. +
Assim, latexmath:[$|7-4x| =12$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$]  latexmath:[$7-4x =12$]  ou latexmath:[$7-4x=-12$] latexmath:[$ \quad \,\Leftrightarrow \quad \,$] 
 latexmath:[$x =-\dfrac{5}{4}$] ou  latexmath:[$x=\dfrac{19}{4}$]. Portanto, latexmath:[$-\frac{5}{4}$] e latexmath:[$\frac{19}{4}$] são raízes de latexmath:[$||7-4x|-3|=9$]. 
.. latexmath:[$|x-2|+3|x-4|=5|x+1|$].

Solução::

Denotemos por latexmath:[$E(x)$] a equação latexmath:[$|x-2|+3|x-4|=5|x+1|$]. Para determinar as raízes desta equação, precisamos igualar cada valor absoluto a zero,  pois precisamos aplicar a definição do valor absoluto a cada termo. Fazendo isto, obtemos latexmath:[$x=2$], latexmath:[$x=4$] e 
latexmath:[$x=-1$]. Agora, precisamos analisar os latexmath:[$4$]  casos a seguir:
+
--
Caso 1: ::: Se latexmath:[$x<-1$], então latexmath:[$ \quad x+1<0  \quad \, \Rightarrow  \quad \, |x+1|=-x-1$], latexmath:[$\quad x-2<-3  \quad \, \Rightarrow  \quad \, |x-2|=-x+2 \quad $] e latexmath:[$\quad x-4<-5  \quad \, \Rightarrow  \quad \, |x-4|=-x+4$]. Logo, latexmath:[$E(x)$] é equivalente a latexmath:[$-x+2-3x+12=-5x-5$]. Assim, latexmath:[$x=-19$] e latexmath:[$-19\in  (-\infty,-1)$].

Caso 2: ::: Se latexmath:[$-1\leq x<2$], então latexmath:[$ \quad 0\leq x+1<3  \quad \, \Rightarrow  \quad \, |x+1|=x+1$], latexmath:[$\quad -3\leq x-2<0  \quad \, \Rightarrow  \quad \, |x-2|=-x+2\quad $] e latexmath:[$\quad -5\leq x-4<-2  \quad \, \Rightarrow  \quad \, |x-4|=-x+4$]. Logo, latexmath:[$E(x)$] é equivalente a latexmath:[$-x+2-3x+12=5x+5$]. Assim, latexmath:[$x=1$] e latexmath:[$1 \in [-1,2)$].

Caso 3: ::: Se latexmath:[$2\leq x<4$], então latexmath:[$ \quad 3\leq x+1<4  \quad \, \Rightarrow  \quad \, |x+1|=x+1$], latexmath:[$\quad 0\leq x-2<2  \quad \, \Rightarrow  \quad \, |x-2|=x-2\quad $] e latexmath:[$\quad -2\leq x-4<0  \quad \, \Rightarrow  \quad \, |x-4|=-x+4$]. Logo, latexmath:[$E(x)$] é equivalente a latexmath:[$x-2-3x+12=5x+5$]. Assim, latexmath:[$x=\dfrac{5}{7}$], porém latexmath:[$\dfrac{5}{7} \not\in [2,4)$].

Caso 4: ::: Se latexmath:[$4\leq x$], então latexmath:[$ \quad 5\leq x+1  \quad \, \Rightarrow  \quad \, |x+1|=x+1$], latexmath:[$\quad 2\leq x-2  \quad \, \Rightarrow  \quad \, |x-2|=x-2\quad $] e latexmath:[$\quad 0\leq x-4  \quad \, \Rightarrow  \quad \, |x-4|=x-4$]. Logo, latexmath:[$E(x)$] é equivalente a latexmath:[$x-2+3x-12=5x+5$]. Assim, latexmath:[$x=-19$], porém latexmath:[$-19 \not \in [4,+\infty)$].
--
+
Portanto, latexmath:[$-19$] e  latexmath:[$1$] são as raízes de latexmath:[$|x-2|+3|x-4|=5|x+1|$].
====


.Resolvamos as seguintes inequações com valor absoluto:
====
.. latexmath:[$\left|\dfrac{1}{x+1}\right|<\left|\dfrac{x}{x^2+2x+1}\right|$].

Solução:: latexmath:[\,]
+
[latexmath]
++++
\[
\left|\dfrac{1}{x+1}\right|<\left|\dfrac{x}{x^2+2x+1}\right|\quad \Leftrightarrow \quad \dfrac{1}{\left|x+1\right|}<\dfrac{\left|x\right|}{\left|x+1\right|^2}
\]
\[\quad \Rightarrow \quad
1<\dfrac{\left|x\right|}{\left|x+1\right|},\quad \mbox{para}\quad x\neq -1\quad \Rightarrow \quad |x+1|<\left|x\right|,\quad \mbox{para}\quad x\neq -1
\]
\[
\quad \Rightarrow \quad |x+1|^2<\left|x\right|^2,\quad \mbox{para}\quad x\neq -1\quad \mbox{para}\quad
x^2+2x+1<x^2,\quad \mbox{para}\quad x\neq -1
\]
\[
\quad \Rightarrow \quad 2x+1 <0,\quad \mbox{para}\quad x\neq -1
\quad \Rightarrow \quad 
x<-\dfrac{1}{2} \quad \mbox{e}\quad x\neq -1.
\]
++++
+
Portanto, latexmath:[$C. S.=(-\infty,-1)\cup\left(-1,-\dfrac{1}{2}\right)$].

.. latexmath:[$\left| \dfrac{x+3}{x+1}\right|<4x+3$].

Solução:: latexmath:[\,]
+
[latexmath]
++++
\[
\left| \dfrac{x+3}{x+1}\right|<4x+3 \quad \Leftrightarrow \quad 4x+3> 0\quad \mbox{ e}\quad  -(4x+3)< \dfrac{x+3}{x+1}<4x+3
\]
\[
 \quad \Leftrightarrow \quad x>-\frac{3}{4} \quad \mbox{ e}\quad \left(-4x-3< \dfrac{x+3}{x+1} \quad \mbox{e} \quad \dfrac{x+3}{x+1}<4x+3\right)
\]
\[
\quad \,\Leftrightarrow \quad x>-\frac{3}{4} \quad \mbox{ e}\quad  \left(0< 4x+3+\dfrac{x+3}{x+1} \quad \mbox{e} \quad 4x+3-\dfrac{x+3}{x+1}>0\right)
\]
\[ \quad \Leftrightarrow \quad x>-\frac{3}{4} \quad \mbox{ e}\quad  \left(0< \dfrac{(4x+3)(x+1)+ x+3}{x+1} \quad \mbox{e} \quad \dfrac{(4x+3)(x+1)-(x+3)}{x+1}>0\right)
\]
\[ \quad \Leftrightarrow \quad x>-\frac{3}{4} \quad \mbox{ e}\quad  \left(0< 2\left(\dfrac{2x^2+4x+3}{x+1}\right) \quad \mbox{e} \quad 2\left(\dfrac{x(2x+3)}{x+1}\right)>0\right)
\]
\[ \quad \Leftrightarrow \quad x>-\frac{3}{4} \quad \mbox{ e}\quad  \left(0< \dfrac{2x^2+4x+3}{x+1} \quad \mbox{e} \quad \dfrac{x(2x+3)}{x+1}>0\right)
\]
++++
+
--
Caso 1::: Encontremos o conjunto solução de latexmath:[$0< \dfrac{2x^2+4x+3}{x+1}$]. Desde que latexmath:[$ 2x^2+4x+3= 0$] não tem raízes reais, então  latexmath:[$C. S. 1=(-1,+\infty)$].

Caso 2::: Encontremos o conjunto solução de latexmath:[$\dfrac{x(2x+3)}{x+1}>0$]. Daqui, latexmath:[$r_1=-\frac{3}{2}$], latexmath:[$ r_2= -1$] e latexmath:[$ r_3= 0$], então  latexmath:[$C. S. 2=\left(-\frac{3}{2},-1\right)\cup (0,+\infty)$].
--
+
Assim, o conjunto solução será obtido intersectando (latexmath:[$C. S. 1$] e latexmath:[$C. S. 2$]) e latexmath:[$x>-\frac{3}{4} $]. Portanto, latexmath:[$C. S.=(0,+\infty)$]  



====


=== Axioma do Supremo


Antes de começar a falar sobre os *limitantes* de um conjunto latexmath:[$A \subset \mathbb{R}$], vejamos alguns conjuntos importantes em latexmath:[$\mathbb{R}$]:
--
* O *conjunto dos números naturais*, denotado por  latexmath:[$\mathbb{N}$], é o conjunto 
+
[latexmath]
++++
\[
\mathbb{N}=\{1,2,3,4,\dots,n-1,n,n+1,\dots\}.
\]
++++ 
+
Se latexmath:[$n \in \mathbb{N}$], então latexmath:[$n$] é dito de *número natural*.

* O *conjunto dos números inteiros*, denotado por  latexmath:[$\mathbb{Z}$], é o conjunto 
+
[latexmath]
++++
\[
\mathbb{Z}=\{\dots,-4,-3,-2,-1,0,1,2,3,4,\dots\}.
\]
++++ 
+
Se latexmath:[$z \in \mathbb{Z}$], então latexmath:[$z$] é dito de *número inteiro*.

* O *conjunto dos números racionais*, denotado por  latexmath:[$\mathbb{Q}$], é o conjunto 
+
[latexmath]
++++
\[
\mathbb{Q}=\left\{\dfrac{a}{b}: a\in \mathbb{Z}\,\,\,\mbox{e}\,\,\, b\in \mathbb{Z},\,\,\,\mbox{com}\,\,\,b \neq 0\right\}.
\]
++++
+
Se latexmath:[$q \in \mathbb{Q}$], então latexmath:[$q$] é dito de *número racional*.

* O *conjunto dos números irracionais*, denotado por  latexmath:[$\mathbb{I}$], é o conjunto 
+
[latexmath]
++++
\[
\mathbb{I}=\{x \in \mathbb{R}: x\not\in \mathbb{Q}\}.
\]
++++ 
+
Se latexmath:[$x \in \mathbb{I}$], então latexmath:[$x$] é dito de *número irracional*.
--
Assim, verifica-se que:
[latexmath]
++++
\[
\mathbb{N}\subset \mathbb{Z}\subset \mathbb{Q}\subset \mathbb{R},\quad  \mathbb{R}=\mathbb{Q}\cup\mathbb{I}\quad\mbox{e}\quad \mathbb{Q}\cap\mathbb{I}=\emptyset.
\]
++++ 

[NOTE]
====
.. Entre os números irracionais temos:
- latexmath:[$\sqrt{2},\,\,\,\sqrt{3},\,\,\,\sqrt[7\]{4},\,\,\,-\sqrt{7},\dots$]
- latexmath:[$\pi=3,141592\dots$]
- latexmath:[$e=2,71828182\dots$]
.. Uma propriedade importante dos números racionais e irracionais é que:
- Entre dois números racionais existe um *número infinito* de números irracionais;
- Entre dois números irracionais existe um *número finito* de números racionais.
====

Definição 1.10::
Seja latexmath:[$A$] um subconjunto não vazio de latexmath:[$\mathbb{R}$]. Diz-se que:

... latexmath:[$A$] é *((limitado superiormente))* se existe  latexmath:[$M \in \mathbb{R}$] tal que
+
[latexmath]
++++
\[
x\leq M,\quad \forall\, x \in A.
\]
++++
+
O número  latexmath:[$M$] é chamado de *limitante superior* de  latexmath:[$A$]. 

... latexmath:[$A$] é *((limitado inferiormente))* se existe  latexmath:[$m \in \mathbb{R}$] tal que
+
[latexmath]
++++
\[
m\leq x,\quad \forall\, x \in A.
\]
++++
+
O número  latexmath:[$m$] é chamado de *limitante inferior* de  latexmath:[$A$].

... latexmath:[$A$] é *limitado* se existe  latexmath:[$k >0$] tal que
+
[latexmath]
++++
\[
|x|\leq k,\quad \forall\, x \in A.
\]
++++
+
Um conjunto é *limitado* se é limitado superiormente e inferiormente.

.{zwsp}
====
.. Os conjuntos latexmath:[$\mathbb{N}$]  e latexmath:[$(-1,+\infty)$] são limitados inferiormente 
pelo limitante latexmath:[$-2$], por exemplo, porém não são limitados superiormente.

.. Os conjuntos latexmath:[$(-\infty,4\]$] e latexmath:[-\mathbb{N}] são conjuntos 
limitados superiormente pelo limitante superior latexmath:[$7$], por exemplo, porém não são limitados inferiormente.

.. Os conjuntos latexmath:[$\left\{\dfrac{2}{3z}:z\in\mathbb{Z}\setminus \{0\} \right\}$] e
 latexmath:[$\{x \in \mathbb{R}: 2x-x^2\geq -7\}$] são limitados por latexmath:[$4$].
====


Definição 1.11::
Seja latexmath:[$A$] um subconjunto não vazio de  latexmath:[$\mathbb{R}$]. Diz-se que:
+
--
... latexmath:[$s\in \mathbb{R}$] é o *((supremo))* de latexmath:[$A$], denotado por latexmath:[${\rm Sup}(A)$] se:
+
--
.. latexmath:[$s$] é limitante superior de latexmath:[$A$], isto é,  latexmath:[$
x\leq s,\,\,\,\forall\,x\in A$].

.. Se latexmath:[$b \in\mathbb{R}$] e latexmath:[$b<s$], então existe  latexmath:[$x\in A$] tal que latexmath:[$b<x\leq s$].
--
... latexmath:[$r\in \mathbb{R}$] é o *((ínfimo))* de latexmath:[$A$], denotado por latexmath:[${\rm Inf}(A)$] se:
+
--
.. latexmath:[$r$] é limitante inferior de latexmath:[$A$], isto é,  latexmath:[$
r\leq x,\,\,\,\forall\,x\in A$].

.. Se latexmath:[$c \in\mathbb{R}$] e latexmath:[$r<c$], então existe  latexmath:[$x\in A$] tal que latexmath:[$r\leq x<c$].
--
--


[NOTE]
====
.. O supremo de um conjunto é o menor limitante superior, e o ínfimo é o maior limitante inferior. 

.. Se o supremo e o ínfimo de um conjunto latexmath:[$A$] pertencem ao conjunto, esses elementos são chamados *máximo* de latexmath:[$A$], denotado por latexmath:[${\rm max}(A)$], e *mínimo* de latexmath:[$A$], denotado por latexmath:[${\rm min}(A)$], respectivamente.

====

.{zwsp}
====
Dados os conjuntos
[latexmath]
++++
\[
A=\left(-1,\dfrac{9}{4}\right],\quad B=\left\{\dfrac{1}{k}:k\in\mathbb{N}\right\}\quad \mbox{e}\quad C=\{x \in \mathbb{Q}: -20\leq x\}
\]
++++
temos que:

.. latexmath:[${\rm Inf}(A)=-1,\,\,\,{\rm Sup}(A)=\dfrac{9}{4}={\rm max}(A)$]. Portanto, latexmath:[$A$] é limitado.

.. latexmath:[${\rm Inf}(B)=0,\,\,\,{\rm Sup}(B)=1={\rm max}(B)$]. Portanto, latexmath:[$B$] é limitado.

.. latexmath:[${\rm Inf}(C)=-20={\rm min}(C)$]. Porém, latexmath:[$C$] não é limitado superiormente, logo, não tem  supremo. Portanto, não é limitado.
====

O axioma a seguir completa os axiomas que definem o sistema dos números reais.

Axioma 11 (Axioma do Supremo)::
Todo subconjunto não vazio, limitado superiormente, latexmath:[$B\subset \mathbb{R}$] 
possui um supremo latexmath:[$s={\rm Sup}(B)\in \mathbb{R}$].


Teorema 1.6::
Seja  latexmath:[$A \subset \mathbb{R}$] com latexmath:[$A\neq \emptyset$]. Se latexmath:[$A$] é 
limitado inferiormente, então este possui ínfimo.

Para finalizar, embora o *princípio da boa ordem* seja muito importante para essa teoria, ele será apenas enunciado. 

Teorema 1.7 (Princípio da boa ordem)::
Todo subconjunto não vazio de latexmath:[$\mathbb{Z}$], limitado inferiormente, possui ínfimo.
 
Este princípio é usado para demonstrar o Princípio da Indução Finita e 
para provar várias propriedades referentes aos números inteiros.



=== Recapitulando

Neste capítulo, apresentamos as noções básicas sobre o conjunto dos *Números Reais* com o intuito de fazer com que o aluno tenha um melhor 
entendimento dos próximos capítulos. 

Desta forma, apresentamos o *sistema dos números reais*, e nele os axiomas que regem a *adição* e *multiplicação*. Seguindo esse raciocínio, apresentamos 
dois teoremas que mostram as propriedades da *substração* e *divisão*. 

Desde que em matemática é importantíssimo entender qual é a *relação de ordem* entre dois elementos quaisquer, visando lidar com 
desigualdades, intervalos, inequações, etc., esse conceito e suas principais propriedades foram revisadas. 

Nas seções subsequentes, trabalhamos os conceitos de *desigualdades*, *intervalos*, *equações*, *inequações* e *valor absoluto*, além de terem sido apresentados exemplos ilustrativos.

Por último, mas não menos importante, o *axioma do supremo* e o *princípio da boa ordem* foram apresentados, estabelecendo-se  
os conceitos de conjuntos limitados inferiormente, superiormente, supremo, ínfimo, máximo e mínimo.
 
No próximo capítulo, apresentaremos as noções básicas sobre relações e funções, já que esta teoria é fundamental para, por exemplo, 
determinar com precisão o domínio e a imagem das funções reais.
 


