Este livro foi projetado e escrito com o objetivo de oferecer aos
estudantes do Curso de Licenciatura em Computação a Distância um
material didático de fácil entendimento dos fundamentos de um curso de
Cálculo Diferencial e Integral. Temos nos esforçado em apresentar o
cálculo de forma não tão rigorosa, isto é, neste livro focamos no uso
da teoria e suas propriedades e não nos aprofundamos nas demonstrações
destas. Priorizamos o uso do desenvolvimento teórico com exemplos e
com uma quantidade razoável de atividades para uma fixação do
conteúdo, de tal forma que resulte de máximo proveito aos estudantes.

A obra é composta por 8 capítulos contendo os principais tópicos
abordados em uma disciplina básica de Cálculo Diferencial e Integral,
e que seguem uma ordem progessiva de conteúdo, por isto recomendamos
ao estudante que dedique tempo e esmero em cada capítulo e resolva a
máxima quantidade de atividades.

No primeiro capítulo se faz uma apresentação axiomática dos números
reais e suas principais propriedades; no segundo capítulo tratamos das
relações e das funções que serão o principal objeto matemático tratado
neste livro; no terceiro capítulo estudamos os conceito de limite,
fundamental para a teoria subsequente; no quarto capítulo estudamos a
continuidade de uma função; no quinto capítulo introduzimos a derivada
de uma função e suas principais propriedades; no sexto capítulo
apresentamos algumas aplicações da derivada; no sétimo capítulo
tratamos da integral indefinida e os métodos de integração; e no
oitavo e último capítulo, introduzimos o conceito da integral definida
e tratamos de algumas das aplicações desta. 

Sabemos que existem vários outros materiais e livros que abordam o
mesmo conteúdo apresentado aqui, alguns até mais abrangentes. Somos
porém, realistas que em uma primeira abordagem demos prioridade a
possibilitar ao aluno familiarizar-se com conceitos básicos e
interpretações, deixando a prova de todos esses resultados a
posteriori.

Esperamos que este livro forneça apoio e incentivo para que o aluno,
depois de aprender estes conceitos, se sinta confiante ao resolver
problemas com aplicações práticas no mundo real.
 

[cols=">", frame="none", topbot="none"]
|====
| João Pessoa, agosto de 2013.

Kely D. V. Villacorta

Felipe A. G. Moreno
|====

=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em Computação, na
modalidade à distância.footnote:[Embora ele tenha sido feito para atender aos alunos
da Universidade Federal da Paraíba, o seu uso não se restringe a esta 
universidade, podendo ser adotado por outras universidades do sistema UAB.]

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

// Sempre manter uma linha em branco no final

